// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for Gender.
const (
	Female Gender = "female"
	Male   Gender = "male"
)

// Valid indicates whether the value is a known member of the Gender enum.
func (e Gender) Valid() bool {
	switch e {
	case Female:
		return true
	case Male:
		return true
	default:
		return false
	}
}

// Defines values for HugType.
const (
	Bear     HugType = "bear"
	Group    HugType = "group"
	Soul     HugType = "soul"
	Standard HugType = "standard"
	Warm     HugType = "warm"
)

// Valid indicates whether the value is a known member of the HugType enum.
func (e HugType) Valid() bool {
	switch e {
	case Bear:
		return true
	case Group:
		return true
	case Soul:
		return true
	case Standard:
		return true
	case Warm:
		return true
	default:
		return false
	}
}

// DailyRewardStatus defines model for DailyRewardStatus.
type DailyRewardStatus struct {
	// CanClaim True when the reward has not been claimed today (UTC).
	CanClaim bool `json:"can_claim"`

	// LastClaimedAt Timestamp of the last successful claim, if any.
	LastClaimedAt *time.Time `json:"last_claimed_at,omitempty"`

	// NextClaimAt UTC timestamp at which the next claim becomes available. Equal to
	// the current time if `can_claim` is true.
	NextClaimAt time.Time `json:"next_claim_at"`

	// StreakDays Current daily streak in days. 0 if never claimed.
	StreakDays int `json:"streak_days"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Gender defines model for Gender.
type Gender string

// HugType defines model for HugType.
type HugType string

// IntimacyInfo defines model for IntimacyInfo.
type IntimacyInfo struct {
	AvailableHugTypes    []HugType `json:"available_hug_types"`
	BonusCoins           int       `json:"bonus_coins"`
	CooldownReductionPct int       `json:"cooldown_reduction_pct"`
	NextTierAt           *int      `json:"next_tier_at,omitempty"`
	RawScore             int       `json:"raw_score"`
	Tier                 int       `json:"tier"`
	TierName             string    `json:"tier_name"`
}

// UpsertUserNoteRequest defines model for UpsertUserNoteRequest.
type UpsertUserNoteRequest struct {
	Content string `json:"content"`
}

// UserListItem defines model for UserListItem.
type UserListItem struct {
	AvgResponseTime     *float32           `json:"avg_response_time,omitempty"`
	DisplayName         *string            `json:"display_name,omitempty"`
	Gender              *Gender            `json:"gender,omitempty"`
	Id                  openapi_types.UUID `json:"id"`
	IsRecentlyActive    bool               `json:"is_recently_active"`
	IsTelegramLinked    bool               `json:"is_telegram_linked"`
	PromotedUntil       *time.Time         `json:"promoted_until,omitempty"`
	PromotionBid        int                `json:"promotion_bid"`
	PromotionMessage    *string            `json:"promotion_message,omitempty"`
	Role                string             `json:"role"`
	SpecialTag          *string            `json:"special_tag,omitempty"`
	Tag                 *string            `json:"tag,omitempty"`
	Username            string             `json:"username"`
	VipCooldownUntil    *time.Time         `json:"vip_cooldown_until,omitempty"`
	VipRemainingSeconds int                `json:"vip_remaining_seconds"`
}

// UserNote defines model for UserNote.
type UserNote struct {
	Content string `json:"content"`

	// TargetDisplayName Only present in the list endpoint.
	TargetDisplayName *string            `json:"target_display_name,omitempty"`
	TargetId          openapi_types.UUID `json:"target_id"`

	// TargetUsername Only present in the list endpoint.
	TargetUsername *string   `json:"target_username,omitempty"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Balance              *int               `json:"balance,omitempty"`
	CaptchaCooldownUntil *time.Time         `json:"captcha_cooldown_until,omitempty"`
	CaptchaType          string             `json:"captcha_type"`
	DisplayName          *string            `json:"display_name,omitempty"`
	Gender               *Gender            `json:"gender,omitempty"`
	HugsGiven            int                `json:"hugs_given"`
	HugsReceived         int                `json:"hugs_received"`
	Id                   openapi_types.UUID `json:"id"`
	Intimacy             *IntimacyInfo      `json:"intimacy,omitempty"`
	IsBlocked            *bool              `json:"is_blocked,omitempty"`
	MutualGiven          *int               `json:"mutual_given,omitempty"`
	MutualReceived       *int               `json:"mutual_received,omitempty"`
	MutualTotal          *int               `json:"mutual_total,omitempty"`
	Rank                 string             `json:"rank"`
	Role                 string             `json:"role"`
	SpecialTag           *string            `json:"special_tag,omitempty"`
	Tag                  *string            `json:"tag,omitempty"`
	TotalHugs            int                `json:"total_hugs"`
	Username             string             `json:"username"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListUserNotesV2Params defines parameters for ListUserNotesV2.
type ListUserNotesV2Params struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchUsersV2Params defines parameters for SearchUsersV2.
type SearchUsersV2Params struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// UpsertUserNoteV2JSONRequestBody defines body for UpsertUserNoteV2 for application/json ContentType.
type UpsertUserNoteV2JSONRequestBody = UpsertUserNoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get daily-reward status
	// (GET /daily-reward/status)
	GetDailyRewardStatus(ctx echo.Context) error
	// List the caller's notes
	// (GET /notes)
	ListUserNotesV2(ctx echo.Context, params ListUserNotesV2Params) error
	// Search users (supports @username prefix)
	// (GET /users/search)
	SearchUsersV2(ctx echo.Context, params SearchUsersV2Params) error
	// Delete the caller's note about the target user
	// (DELETE /users/{usernameOrId}/note)
	DeleteUserNoteV2(ctx echo.Context, usernameOrId string) error
	// Get the caller's note about the target user
	// (GET /users/{usernameOrId}/note)
	GetUserNoteV2(ctx echo.Context, usernameOrId string) error
	// Create or update the caller's note about the target user
	// (PUT /users/{usernameOrId}/note)
	UpsertUserNoteV2(ctx echo.Context, usernameOrId string) error
	// Get user profile (by UUID or username)
	// (GET /users/{usernameOrId}/profile)
	GetUserProfileV2(ctx echo.Context, usernameOrId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetDailyRewardStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetDailyRewardStatus(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDailyRewardStatus(ctx)
	return err
}

// ListUserNotesV2 converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserNotesV2(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserNotesV2Params
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserNotesV2(ctx, params)
	return err
}

// SearchUsersV2 converts echo context to params.
func (w *ServerInterfaceWrapper) SearchUsersV2(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersV2Params
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchUsersV2(ctx, params)
	return err
}

// DeleteUserNoteV2 converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserNoteV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "usernameOrId" -------------
	var usernameOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "usernameOrId", ctx.Param("usernameOrId"), &usernameOrId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter usernameOrId: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserNoteV2(ctx, usernameOrId)
	return err
}

// GetUserNoteV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserNoteV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "usernameOrId" -------------
	var usernameOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "usernameOrId", ctx.Param("usernameOrId"), &usernameOrId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter usernameOrId: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserNoteV2(ctx, usernameOrId)
	return err
}

// UpsertUserNoteV2 converts echo context to params.
func (w *ServerInterfaceWrapper) UpsertUserNoteV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "usernameOrId" -------------
	var usernameOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "usernameOrId", ctx.Param("usernameOrId"), &usernameOrId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter usernameOrId: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpsertUserNoteV2(ctx, usernameOrId)
	return err
}

// GetUserProfileV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfileV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "usernameOrId" -------------
	var usernameOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "usernameOrId", ctx.Param("usernameOrId"), &usernameOrId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter usernameOrId: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfileV2(ctx, usernameOrId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/daily-reward/status", wrapper.GetDailyRewardStatus, options.OperationMiddlewares["getDailyRewardStatus"]...)
	router.GET(options.BaseURL+"/notes", wrapper.ListUserNotesV2, options.OperationMiddlewares["listUserNotesV2"]...)
	router.GET(options.BaseURL+"/users/search", wrapper.SearchUsersV2, options.OperationMiddlewares["searchUsersV2"]...)
	router.DELETE(options.BaseURL+"/users/:usernameOrId/note", wrapper.DeleteUserNoteV2, options.OperationMiddlewares["deleteUserNoteV2"]...)
	router.GET(options.BaseURL+"/users/:usernameOrId/note", wrapper.GetUserNoteV2, options.OperationMiddlewares["getUserNoteV2"]...)
	router.PUT(options.BaseURL+"/users/:usernameOrId/note", wrapper.UpsertUserNoteV2, options.OperationMiddlewares["upsertUserNoteV2"]...)
	router.GET(options.BaseURL+"/users/:usernameOrId/profile", wrapper.GetUserProfileV2, options.OperationMiddlewares["getUserProfileV2"]...)

}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetDailyRewardStatusRequestObject struct {
}

type GetDailyRewardStatusResponseObject interface {
	VisitGetDailyRewardStatusResponse(w http.ResponseWriter) error
}

type GetDailyRewardStatus200JSONResponse DailyRewardStatus

func (response GetDailyRewardStatus200JSONResponse) VisitGetDailyRewardStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDailyRewardStatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetDailyRewardStatus401JSONResponse) VisitGetDailyRewardStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserNotesV2RequestObject struct {
	Params ListUserNotesV2Params
}

type ListUserNotesV2ResponseObject interface {
	VisitListUserNotesV2Response(w http.ResponseWriter) error
}

type ListUserNotesV2200JSONResponse []UserNote

func (response ListUserNotesV2200JSONResponse) VisitListUserNotesV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserNotesV2401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListUserNotesV2401JSONResponse) VisitListUserNotesV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SearchUsersV2RequestObject struct {
	Params SearchUsersV2Params
}

type SearchUsersV2ResponseObject interface {
	VisitSearchUsersV2Response(w http.ResponseWriter) error
}

type SearchUsersV2200JSONResponse []UserListItem

func (response SearchUsersV2200JSONResponse) VisitSearchUsersV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchUsersV2401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SearchUsersV2401JSONResponse) VisitSearchUsersV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserNoteV2RequestObject struct {
	UsernameOrId string `json:"usernameOrId"`
}

type DeleteUserNoteV2ResponseObject interface {
	VisitDeleteUserNoteV2Response(w http.ResponseWriter) error
}

type DeleteUserNoteV2204Response struct {
}

func (response DeleteUserNoteV2204Response) VisitDeleteUserNoteV2Response(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUserNoteV2401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteUserNoteV2401JSONResponse) VisitDeleteUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteUserNoteV2404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteUserNoteV2404JSONResponse) VisitDeleteUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserNoteV2RequestObject struct {
	UsernameOrId string `json:"usernameOrId"`
}

type GetUserNoteV2ResponseObject interface {
	VisitGetUserNoteV2Response(w http.ResponseWriter) error
}

type GetUserNoteV2200JSONResponse UserNote

func (response GetUserNoteV2200JSONResponse) VisitGetUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserNoteV2401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserNoteV2401JSONResponse) VisitGetUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserNoteV2404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUserNoteV2404JSONResponse) VisitGetUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertUserNoteV2RequestObject struct {
	UsernameOrId string `json:"usernameOrId"`
	Body         *UpsertUserNoteV2JSONRequestBody
}

type UpsertUserNoteV2ResponseObject interface {
	VisitUpsertUserNoteV2Response(w http.ResponseWriter) error
}

type UpsertUserNoteV2200JSONResponse UserNote

func (response UpsertUserNoteV2200JSONResponse) VisitUpsertUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertUserNoteV2400JSONResponse struct{ BadRequestJSONResponse }

func (response UpsertUserNoteV2400JSONResponse) VisitUpsertUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertUserNoteV2401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpsertUserNoteV2401JSONResponse) VisitUpsertUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertUserNoteV2404JSONResponse struct{ NotFoundJSONResponse }

func (response UpsertUserNoteV2404JSONResponse) VisitUpsertUserNoteV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserProfileV2RequestObject struct {
	UsernameOrId string `json:"usernameOrId"`
}

type GetUserProfileV2ResponseObject interface {
	VisitGetUserProfileV2Response(w http.ResponseWriter) error
}

type GetUserProfileV2200JSONResponse UserProfile

func (response GetUserProfileV2200JSONResponse) VisitGetUserProfileV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserProfileV2401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserProfileV2401JSONResponse) VisitGetUserProfileV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserProfileV2404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUserProfileV2404JSONResponse) VisitGetUserProfileV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get daily-reward status
	// (GET /daily-reward/status)
	GetDailyRewardStatus(ctx context.Context, request GetDailyRewardStatusRequestObject) (GetDailyRewardStatusResponseObject, error)
	// List the caller's notes
	// (GET /notes)
	ListUserNotesV2(ctx context.Context, request ListUserNotesV2RequestObject) (ListUserNotesV2ResponseObject, error)
	// Search users (supports @username prefix)
	// (GET /users/search)
	SearchUsersV2(ctx context.Context, request SearchUsersV2RequestObject) (SearchUsersV2ResponseObject, error)
	// Delete the caller's note about the target user
	// (DELETE /users/{usernameOrId}/note)
	DeleteUserNoteV2(ctx context.Context, request DeleteUserNoteV2RequestObject) (DeleteUserNoteV2ResponseObject, error)
	// Get the caller's note about the target user
	// (GET /users/{usernameOrId}/note)
	GetUserNoteV2(ctx context.Context, request GetUserNoteV2RequestObject) (GetUserNoteV2ResponseObject, error)
	// Create or update the caller's note about the target user
	// (PUT /users/{usernameOrId}/note)
	UpsertUserNoteV2(ctx context.Context, request UpsertUserNoteV2RequestObject) (UpsertUserNoteV2ResponseObject, error)
	// Get user profile (by UUID or username)
	// (GET /users/{usernameOrId}/profile)
	GetUserProfileV2(ctx context.Context, request GetUserProfileV2RequestObject) (GetUserProfileV2ResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetDailyRewardStatus operation middleware
func (sh *strictHandler) GetDailyRewardStatus(ctx echo.Context) error {
	var request GetDailyRewardStatusRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDailyRewardStatus(ctx.Request().Context(), request.(GetDailyRewardStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDailyRewardStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDailyRewardStatusResponseObject); ok {
		return validResponse.VisitGetDailyRewardStatusResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListUserNotesV2 operation middleware
func (sh *strictHandler) ListUserNotesV2(ctx echo.Context, params ListUserNotesV2Params) error {
	var request ListUserNotesV2RequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListUserNotesV2(ctx.Request().Context(), request.(ListUserNotesV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUserNotesV2")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListUserNotesV2ResponseObject); ok {
		return validResponse.VisitListUserNotesV2Response(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchUsersV2 operation middleware
func (sh *strictHandler) SearchUsersV2(ctx echo.Context, params SearchUsersV2Params) error {
	var request SearchUsersV2RequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchUsersV2(ctx.Request().Context(), request.(SearchUsersV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchUsersV2")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchUsersV2ResponseObject); ok {
		return validResponse.VisitSearchUsersV2Response(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteUserNoteV2 operation middleware
func (sh *strictHandler) DeleteUserNoteV2(ctx echo.Context, usernameOrId string) error {
	var request DeleteUserNoteV2RequestObject

	request.UsernameOrId = usernameOrId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUserNoteV2(ctx.Request().Context(), request.(DeleteUserNoteV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUserNoteV2")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteUserNoteV2ResponseObject); ok {
		return validResponse.VisitDeleteUserNoteV2Response(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserNoteV2 operation middleware
func (sh *strictHandler) GetUserNoteV2(ctx echo.Context, usernameOrId string) error {
	var request GetUserNoteV2RequestObject

	request.UsernameOrId = usernameOrId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserNoteV2(ctx.Request().Context(), request.(GetUserNoteV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserNoteV2")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserNoteV2ResponseObject); ok {
		return validResponse.VisitGetUserNoteV2Response(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpsertUserNoteV2 operation middleware
func (sh *strictHandler) UpsertUserNoteV2(ctx echo.Context, usernameOrId string) error {
	var request UpsertUserNoteV2RequestObject

	request.UsernameOrId = usernameOrId

	var body UpsertUserNoteV2JSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpsertUserNoteV2(ctx.Request().Context(), request.(UpsertUserNoteV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpsertUserNoteV2")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpsertUserNoteV2ResponseObject); ok {
		return validResponse.VisitUpsertUserNoteV2Response(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserProfileV2 operation middleware
func (sh *strictHandler) GetUserProfileV2(ctx echo.Context, usernameOrId string) error {
	var request GetUserProfileV2RequestObject

	request.UsernameOrId = usernameOrId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserProfileV2(ctx.Request().Context(), request.(GetUserProfileV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserProfileV2")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserProfileV2ResponseObject); ok {
		return validResponse.VisitGetUserProfileV2Response(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FrNcts48n+VLvz/VWtXUR/WZOagUzKJJ/FWdpKK7Z1D5KIgskViDAIMAMrWplS1173vI+yTzZNsNUBR",
	"lETFysTJztZeYokEGo3uX//6Q/nIEl2UWqFylo0/MoO21Mqi//IjT9/hhwqto2+JVg6V/8jLUoqEO6HV",
	"4FerFT2zSY4Fp0//b3DOxuz/BhvRg/DWDs6N0YatVquIpWgTI0oSwsbsQi24FCmY+sBVxH7W7iddqfTr",
	"H/4Ora5MgqC0g7k/cxWxa8Url2sj/obfQIe/CGuFykAbELUteJKgteD0LSpGO2ohdMYLLuTyHd5xk146",
	"7ir/sDS6RONEcF/CVZxILgr6sn3YlakQ7nJU4HIE48VAzq03wAxRgd+IKTid8iWcXF89P+2ziLlliWzM",
	"ZlpL5IqsJLl1cb065q7jLFGgdbwoQc/9cbQDbOUvN69kOCoCMQeulnTIXJuCJLGUO+w5USCLmKqk5DOJ",
	"bOxMhY0m1hmhMlJE4X2tSKca11fPwTWqcAd3uUhyrxDtDFrADBNdoAW+4MIf14fzDxWX4PRE0dqkMgaV",
	"86JI5Wlj5SkIC6Rbf6IOXWJPaesM8ts45Uu7r/Lz+qyUfA1hKQgFtLoPQzpe4QLN2lktBwnlMEPjUUMh",
	"JQxh+H0LE7sG29blppGkZ79i4uMxQHcfZjpF+rt3twKt5VnXu12lSMJmfdfZL1Gl6A9HVRW0qeCSNs3R",
	"f7jpsO2rKrvyzzabrOMq5SZlEZshNyximdFVySJ2xw3ZxOpKdgq7UE4UPFleqLnet0EDlzivspg2+8fC",
	"YWEfYoS1mqvmVG4MX9L3mVaVjRMtlG1ZsfFtxBKtZarvVGwwrRKCTVwmrnutd7cTaOrwOBBQrR2G38U2",
	"0Qa7BZKsw29ixYsjfL85oxbY3n3wglGnxbcN1gWj69KicdcWzc/aYSu57UK6YfqC379GlbmcjUff/xCx",
	"Qqj197PoQVwHMZ2aWDSvhXUXDosuPGXxOhXHnjsOO0xVxSyYPRW2lHzZWP5BysyaqPoUQOvYW0VM+DzY",
	"MFtVibSL1ISNDSaonFzGPHFi0cZBK3UIGzuUmBlexFKo25Bm99eVRhfaYRpXygm5pcJnZYgghzA0E2k3",
	"cjdLWuz1oGCjZTcF2hITwWXseHaUoGPXVRbNgfiK2EKUcRM3X2gykmWw4EIJlcUWE63STi7agb4HRqNl",
	"baFOj3fCZddXhxQ5FFkU3Y8X1uQXk6GLdwNsO12/UXIJpUFLOVuE0koK6wBVWmqhXP8Yi9dHHRlq9eo2",
	"Hn6HUvv4Kgkl63rumFJmx/+bW0SN2bfEHvLcW6PnQnY4b8YlV8mBVJTw0iU5fzTYr+W5un7YW/DVqTav",
	"MhtnYoGq+8b+PYWNWOABLjuWrevK5iHdtiqgwN4zqZODrF1UruLyU3eoV3z6FvUipx2X3SsMV7edTvrm",
	"tOyVpILkQLn2Cdo+jj9bqNiFwNbptVF2gLwfc2QLTCoj3PKS3Fz3/cgNmmcVseFHXyij+WkNoz//csXq",
	"TtQ73L/d4Cp3rgztragr5W0+WozAVmbOE4S5Np6O3r578+JVlVkoJXcE1z5clpj05sJYF0GGCg3RBrjc",
	"6CrLJ2qqeSl61DZkqKaA9zxxcglS3CIszuBk6z30Eq3mIoP2w95i1F8WcqJ4KQa6RPrrn/FCTk/78Iqr",
	"VKKxIMUCiTen5EajuBw4w5UttXEDuutgMRpM+xM1UYtRw6k2Aq3A6ablXZyBRbMQCXW/SzRj2gDQg5fn",
	"VzAgP9uBRW6SHGxVknALXMGEPV1jYMKIxefiHlzOHcyFdKTebElyANbLwFazACnQxPwnSkObq6DgLslP",
	"+3unf1xLeGMu0tWgDDTsRxCls4DC5WiAw/X1xQvQ9KnRzCtwor2HuQzpZi7uMYU74XK6xISdrnNPyV3e",
	"Pt33tr0wgRhYP8mgPpqDQZ72/B3qp0mOyW0DGr8vHF2PL05CB183BkIKtwSuUt/d98I7ov/W3Qdvr68G",
	"L85fn1+dHzCD0o5MpniG/tSES4nmTxZKIxbc1Xcv0fRCwgO/4eQs/C3RQMmFieC3f/xr9P0PcK0E4Q/8",
	"PwEpp324RDnvBUm0zQI3CFxKfYcpzJaQohWZahstLKM0brfVCi+0SdGEvaGwgpB4bcDpGZwMCPaLs1My",
	"tXVCSg9PTIFbkJjxZBmGGE44ojvmw5OTWy5rGD97ewG//f2fsBhRcYbGhvAe9Yf9IVFdHVNszL7rD/vf",
	"UUXHXe7ppcvn9DzDjrHNu10Y1BHVXDkMR4KwPlxbcpSw4DQYn0xp9UTV053KOa28JKQILXSlnEeprhy5",
	"i9iHYoeHkUowAlUhftR3kbIxe4luf/YWbQ9OR8Phow0M9w/rGB6uJ0W1MVcRezI8OyS5UXWwNeFsJwM2",
	"fr+dBt77ZER9d1oIxW5WNxGzVVFwsww2gbZTGz1WEQtgbfl325zUA68rdvvXkceJ4QUSu3ktBN3vQ4Vm",
	"SYWbT55MikK4dRbiATRzXknHxt8PIyruRVEVbHw2HPrSvv7WNR3rPkDP5xYPnNAWOewQefOFYDhqaNQ0",
	"OXtTo31wkIkpbGpy8R4P7LAJpG8OGa/UPncFyLQT4kFmuGwyXZ05eWK0tZtUSOTfzn19+GU98Z5+mE5U",
	"AzSCK2Vcn66mT6dR6JKQpyR9+nQaaNKIsiSKVGnglNCOEsUIG/Iqvc24UNbBdK3GNCRi4sr9RIx2oojt",
	"U6NJdhffXPrLkb+PDo8PW8Bttbo/POno2z47xEb/OyHWTOg+I8y8Ywk4HsXfPLACXsLhcNJUk00hWVdn",
	"p+1I66h6gj8khk/bkHzhn68pyKNyxx1P9sM1bErhRJv6Vwu8F9Zhevo7TUSbnjy8qfkV8QtsGnTfpyvg",
	"Myoc6Hld/3kpvt3vyHUv0X3KaI9XM2yywz5Mr3L/Myf+8a1OVcVnmLyLGKnm3FBOG+Ws3W+Hdn5j212O",
	"vIlYWXU4dPvnhNqn/jeFH3W6fDx3dv5qsdqeGdAdVv8hTNFzSAz6Ll2but2o0TJ8GC2t/2jwh0flc3/N",
	"zS2Ph+hBvi03M8/OSudZ3YR3dd9bfTU826patAqFymatbfpKqmKaksY3f6ZnRYoHWp7WaPZgFfJ4wfZV",
	"QbyeMHfgmF7D2hv/FfxYtTSGk9myQcja/KfhnsHDwVmVkWzMwghgxFY3q38HAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
