// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for Gender.
const (
	Female Gender = "female"
	Male   Gender = "male"
)

// Valid indicates whether the value is a known member of the Gender enum.
func (e Gender) Valid() bool {
	switch e {
	case Female:
		return true
	case Male:
		return true
	default:
		return false
	}
}

// Defines values for HugType.
const (
	Bear     HugType = "bear"
	Group    HugType = "group"
	Soul     HugType = "soul"
	Standard HugType = "standard"
	Warm     HugType = "warm"
)

// Valid indicates whether the value is a known member of the HugType enum.
func (e HugType) Valid() bool {
	switch e {
	case Bear:
		return true
	case Group:
		return true
	case Soul:
		return true
	case Standard:
		return true
	case Warm:
		return true
	default:
		return false
	}
}

// DailyRewardStatus defines model for DailyRewardStatus.
type DailyRewardStatus struct {
	// CanClaim True when the reward has not been claimed today (UTC).
	CanClaim bool `json:"can_claim"`

	// LastClaimedAt Timestamp of the last successful claim, if any.
	LastClaimedAt *time.Time `json:"last_claimed_at,omitempty"`

	// NextClaimAt UTC timestamp at which the next claim becomes available. Equal to
	// the current time if `can_claim` is true.
	NextClaimAt time.Time `json:"next_claim_at"`

	// StreakDays Current daily streak in days. 0 if never claimed.
	StreakDays int `json:"streak_days"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Gender defines model for Gender.
type Gender string

// HugType defines model for HugType.
type HugType string

// IntimacyInfo defines model for IntimacyInfo.
type IntimacyInfo struct {
	AvailableHugTypes    []HugType `json:"available_hug_types"`
	BonusCoins           int       `json:"bonus_coins"`
	CooldownReductionPct int       `json:"cooldown_reduction_pct"`
	NextTierAt           *int      `json:"next_tier_at,omitempty"`
	RawScore             int       `json:"raw_score"`
	Tier                 int       `json:"tier"`
	TierName             string    `json:"tier_name"`
}

// UserListItem defines model for UserListItem.
type UserListItem struct {
	AvgResponseTime     *float32           `json:"avg_response_time,omitempty"`
	DisplayName         *string            `json:"display_name,omitempty"`
	Gender              *Gender            `json:"gender,omitempty"`
	Id                  openapi_types.UUID `json:"id"`
	IsRecentlyActive    bool               `json:"is_recently_active"`
	IsTelegramLinked    bool               `json:"is_telegram_linked"`
	PromotedUntil       *time.Time         `json:"promoted_until,omitempty"`
	PromotionBid        int                `json:"promotion_bid"`
	PromotionMessage    *string            `json:"promotion_message,omitempty"`
	Role                string             `json:"role"`
	SpecialTag          *string            `json:"special_tag,omitempty"`
	Tag                 *string            `json:"tag,omitempty"`
	Username            string             `json:"username"`
	VipCooldownUntil    *time.Time         `json:"vip_cooldown_until,omitempty"`
	VipRemainingSeconds int                `json:"vip_remaining_seconds"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Balance              *int               `json:"balance,omitempty"`
	CaptchaCooldownUntil *time.Time         `json:"captcha_cooldown_until,omitempty"`
	CaptchaType          string             `json:"captcha_type"`
	DisplayName          *string            `json:"display_name,omitempty"`
	Gender               *Gender            `json:"gender,omitempty"`
	HugsGiven            int                `json:"hugs_given"`
	HugsReceived         int                `json:"hugs_received"`
	Id                   openapi_types.UUID `json:"id"`
	Intimacy             *IntimacyInfo      `json:"intimacy,omitempty"`
	IsBlocked            *bool              `json:"is_blocked,omitempty"`
	MutualGiven          *int               `json:"mutual_given,omitempty"`
	MutualReceived       *int               `json:"mutual_received,omitempty"`
	MutualTotal          *int               `json:"mutual_total,omitempty"`
	Rank                 string             `json:"rank"`
	Role                 string             `json:"role"`
	SpecialTag           *string            `json:"special_tag,omitempty"`
	Tag                  *string            `json:"tag,omitempty"`
	TotalHugs            int                `json:"total_hugs"`
	Username             string             `json:"username"`
}

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// SearchUsersV2Params defines parameters for SearchUsersV2.
type SearchUsersV2Params struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get daily-reward status
	// (GET /daily-reward/status)
	GetDailyRewardStatus(ctx echo.Context) error
	// Search users (supports @username prefix)
	// (GET /users/search)
	SearchUsersV2(ctx echo.Context, params SearchUsersV2Params) error
	// Get user profile (by UUID or username)
	// (GET /users/{usernameOrId}/profile)
	GetUserProfileV2(ctx echo.Context, usernameOrId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetDailyRewardStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetDailyRewardStatus(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDailyRewardStatus(ctx)
	return err
}

// SearchUsersV2 converts echo context to params.
func (w *ServerInterfaceWrapper) SearchUsersV2(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersV2Params
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchUsersV2(ctx, params)
	return err
}

// GetUserProfileV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfileV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "usernameOrId" -------------
	var usernameOrId string

	err = runtime.BindStyledParameterWithOptions("simple", "usernameOrId", ctx.Param("usernameOrId"), &usernameOrId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter usernameOrId: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfileV2(ctx, usernameOrId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/daily-reward/status", wrapper.GetDailyRewardStatus, options.OperationMiddlewares["getDailyRewardStatus"]...)
	router.GET(options.BaseURL+"/users/search", wrapper.SearchUsersV2, options.OperationMiddlewares["searchUsersV2"]...)
	router.GET(options.BaseURL+"/users/:usernameOrId/profile", wrapper.GetUserProfileV2, options.OperationMiddlewares["getUserProfileV2"]...)

}

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetDailyRewardStatusRequestObject struct {
}

type GetDailyRewardStatusResponseObject interface {
	VisitGetDailyRewardStatusResponse(w http.ResponseWriter) error
}

type GetDailyRewardStatus200JSONResponse DailyRewardStatus

func (response GetDailyRewardStatus200JSONResponse) VisitGetDailyRewardStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDailyRewardStatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetDailyRewardStatus401JSONResponse) VisitGetDailyRewardStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SearchUsersV2RequestObject struct {
	Params SearchUsersV2Params
}

type SearchUsersV2ResponseObject interface {
	VisitSearchUsersV2Response(w http.ResponseWriter) error
}

type SearchUsersV2200JSONResponse []UserListItem

func (response SearchUsersV2200JSONResponse) VisitSearchUsersV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchUsersV2401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SearchUsersV2401JSONResponse) VisitSearchUsersV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserProfileV2RequestObject struct {
	UsernameOrId string `json:"usernameOrId"`
}

type GetUserProfileV2ResponseObject interface {
	VisitGetUserProfileV2Response(w http.ResponseWriter) error
}

type GetUserProfileV2200JSONResponse UserProfile

func (response GetUserProfileV2200JSONResponse) VisitGetUserProfileV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserProfileV2401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserProfileV2401JSONResponse) VisitGetUserProfileV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserProfileV2404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUserProfileV2404JSONResponse) VisitGetUserProfileV2Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get daily-reward status
	// (GET /daily-reward/status)
	GetDailyRewardStatus(ctx context.Context, request GetDailyRewardStatusRequestObject) (GetDailyRewardStatusResponseObject, error)
	// Search users (supports @username prefix)
	// (GET /users/search)
	SearchUsersV2(ctx context.Context, request SearchUsersV2RequestObject) (SearchUsersV2ResponseObject, error)
	// Get user profile (by UUID or username)
	// (GET /users/{usernameOrId}/profile)
	GetUserProfileV2(ctx context.Context, request GetUserProfileV2RequestObject) (GetUserProfileV2ResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetDailyRewardStatus operation middleware
func (sh *strictHandler) GetDailyRewardStatus(ctx echo.Context) error {
	var request GetDailyRewardStatusRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDailyRewardStatus(ctx.Request().Context(), request.(GetDailyRewardStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDailyRewardStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDailyRewardStatusResponseObject); ok {
		return validResponse.VisitGetDailyRewardStatusResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchUsersV2 operation middleware
func (sh *strictHandler) SearchUsersV2(ctx echo.Context, params SearchUsersV2Params) error {
	var request SearchUsersV2RequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchUsersV2(ctx.Request().Context(), request.(SearchUsersV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchUsersV2")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchUsersV2ResponseObject); ok {
		return validResponse.VisitSearchUsersV2Response(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserProfileV2 operation middleware
func (sh *strictHandler) GetUserProfileV2(ctx echo.Context, usernameOrId string) error {
	var request GetUserProfileV2RequestObject

	request.UsernameOrId = usernameOrId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserProfileV2(ctx.Request().Context(), request.(GetUserProfileV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserProfileV2")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserProfileV2ResponseObject); ok {
		return validResponse.VisitGetUserProfileV2Response(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFnvctvIDX8VzLYztWdkyfZl+sGfkia5xJ1rLxPbvQ+Rh4JIiNzzcpfZP3LYjGb6EH3CPkkHuxRNWVTi",
	"Nnf5ZJHEAljg9wMW688iN3VjNGnvxMVnYck1RjuKD383/kcTdMG/c6M9ac8/sWmUzNFLo2e/OqP5ncsr",
	"qpF//dHSSlyIP8weFM/SVzd7ba2xYrPZTERBLreyYSXiQrwnZ4LNCbTxsIo2NxNxozH4ylj5T/oOPvxN",
	"Oid1CcaC1GtUsgDMc3IOvLkjLXhFp4RtvEKp2vd0j7a48uhDfNlY05D1MsUvR53lCmXND7vGrm0guK9I",
	"g68IbFQDFboYgCWRhriQCvCmwBaObq5fHk/FRPi2IXEhlsYoQs1RUuh81kln6EdsyZqcx7oBs4rmeAW4",
	"EDe3CiqZmoBcAeqWjayMrVmTKNDTiZc1iYnQQSlcKhIX3gbqPXHeSl2yI5o+dY6MunFz/RJ87wp6uK9k",
	"XkWHeGXyApaUm5oc4BplNDeF1x8DKvBmrlk2D9aS9lEVu7zoo7wA6YB9m871oU3sOe28JbzLCmzdvssv",
	"O1sF5xqSKEgNLD2FUzavaU12m6xBgqT2VJKNqLH0MUjLGP4wwMTjgO36cttrMstfKffsa4LuPsxMQfx3",
	"b281OYfl2LfHTrGGB/kx229IFxSNkw41L6pR8aIVxR+3I7F9G8rr+O5hkfOoC7SFmIgloRUTUVoTGjER",
	"92g5Js4ENarsUntZY95e6pXZj0EPl6wKZcaL42vpqXZfqwhbNze9VbQWW35eGh1clhup3SCKfW4nIjdG",
	"FeZeZ5aKkDNssib347Ix3V6S7ehxgFCDFRbvM5cbS+MKWdfhL5nG+gm5f7DRKRyuPrjByWjEdwM2BqMb",
	"R/Yn6fylp3osi2W27UBZZOzhMOlQL9NmC+kahW2/368WqrLH8pdg0SF+MxEydp++noQgi7FSIl1mKSft",
	"VZth7uV6GP1BwZYu86SotFhnSuq71Nz25RprauOpyIL2Uu248D/V5aSHM7eUxTheHkQGNeOriq1R44XH",
	"NZRLVJnH8kmKnioXHNkDqJ6ItWyyHq3fGDLWZalGqaUuM0e50cVoBXhEpgiM3ssuQqMZH4XL41wdcuQQ",
	"s95Zs5IpJ7vEWqJCnR8oIzk2Pq/wNwveVp/vav+ewO9O2CqULivlmvT4juN3Dr5c0wFGPJXzXVf6mm87",
	"3SvVgKUy+UHu18EHVF/aQyfx5V10Qt54VOMSFvXdaJK+O7mjk9xMDrTaL5D/aSwcoOIxBHasd0F5BOR9",
	"znEsKA9W+vaK05yo9hdCS/ZF8FUkXnz6cQujv/5yLbopIiY8fn3AVeV9k0YT2Z1yds+j63Nwwa4wJ1gZ",
	"G4/O797//OptKB00Cj3DdQpXDeUnK2mdn0BJmix6niMqa0JZzfXCYCNP+MhXkl4AfcLcqxaUvCNYn8HR",
	"znc4yY1eyRKGL0/W59O2VnONjZyZhvhvfIe1WhxP4S3qQpF1oOSa+Ly84DRajWrmLWrXGOtnvNfZ+ny2",
	"mM71XK/PAYvCsZdEQLpojNTegdHgTT+4rM/AkV3LnGeYluwFLwU4gTevr2HGGXczR2jzClxo2IwD1DAX",
	"z7domAtoLK3kJ/AVelhJ5dnRZct6ALZi4MIygQuMVi0caQPDqgU1+rw6nu5Z/7zV8LO9LDazJhXkOEg2",
	"3gFJX5EFhJuby1c8aWJvMjlwZGKuUam2c5QKuJe+4k3MxTFHkyPRoK+G1uOEcpLmyJmL8yhPQwiWsDiJ",
	"e+je5hXldz184rpkuhtCj9Ic1h3vpJK+BdRFnNFO0jduBMcpbWdwNGMUrM+O2Z7zUqmYIyoAHSgqMW/T",
	"POalZ/aLiFZk3666XL54dwn/+de/YX3OHY+sS2g/n55OT5n5HcTEhfhhejr9gdsk+iqybWzj/L6kkQn0",
	"/eNYdLDKUSmyf3LdnJeUTeHGEfiKZ0oDNvYWlp7rblAN3hsdNRHDtDZB+5gqEzw0ZJmMDCBM02EKAjfl",
	"eGtxWYgL8Yb8/jXCZPcS5vz09De7+9g3NnIPsh16u2BuJuLZ6dkhzb2rs53LmmFtFBcfdqvih1ibeYQo",
	"aqnF7eZ2Ilyoa7RtigkMk9r7sZmIHYofTPNVz92uFmBujXMP5GY4D9k8hV+2NzGLj4u5btBiTZ4s2+Ya",
	"Egm4eL6YpOsTwoK1L54vEuatbBrGuy4SQNKBjfEiXaoU/LVEqZ2HxdaNRSotDPz90kJurtESFNaw7jHw",
	"XMXN8bHP/eM8cqLz2sWISw7Fx0C25TNb7Jvi47b5RKTU+Okn0iWn5M/PJvs9dVyHkrX0O3oKWmFQXlyc",
	"n05Yqax51j875Sepu6exi5FxA2a1cnTAwlDl6YjK228kz5PuC3Zm2L1Lg31CsSyXmphYBk5E8XcnVsJL",
	"Mg5HfX/sW2PXb46HTBtvZweZ96Jrc2P9badzwYsdFhmdiPMg6wCVMvcdq3qKxc5iT5ws6EA9HYxBB1nB",
	"LjzgbbhFMTxIpnPqAzgeE+T2d6zUw2luBFL8GbbZ+P+AxIuefX1R/z+AbyzpYeAxHC3bHiHb8B+nfaYM",
	"p2QFq8SFSOeLc7G53fw3AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
