// Package v2 implements the /api/v2 HTTP layer.
//
// Like v1, v2 is spec-first: the OpenAPI document at `api/openapi-v2.yaml`
// is the source of truth and `api.gen.go` is regenerated by:
//
//	oapi-codegen -config oapi-codegen-v2.yml api/openapi-v2.yaml
//
// Endpoints surfaced by v2:
//
//	GET /api/v2/users/search               — search users; "@username" prefix
//	                                          filters by username substring only
//	                                          (no display_name match).
//	GET /api/v2/users/{usernameOrId}/profile
//	                                       — profile lookup by UUID or username
//	                                          (with optional leading "@").
//	GET /api/v2/daily-reward/status        — read-only daily-reward status.
//
// v1 (/api/v1) remains as legacy.
package v2

import (
	"context"
	"errors"
	"strings"
	"time"

	"go-service-template/internal/errorz"
	"go-service-template/internal/models"

	"github.com/google/uuid"
)

// hugService is the subset of the v1 hug service consumed by v2 handlers.
type hugService interface {
	GetUserProfile(ctx context.Context, userID uuid.UUID, viewerID *uuid.UUID) (*models.User, *models.UserStats, *models.Balance, *models.MutualHugStats, bool, *models.IntimacyInfo, error)
	SearchUsers(ctx context.Context, query string, viewerID uuid.UUID, limit, offset int32) ([]*models.User, error)
	GetDailyRewardStatus(ctx context.Context, userID uuid.UUID) (bool, time.Time, int32, *time.Time, error)
}

// userService is the subset of the v1 user service consumed by v2 handlers.
type userService interface {
	GetByUsername(ctx context.Context, username string) (*models.User, error)
}

type Handler struct {
	hugSvc  hugService
	userSvc userService
}

func New(hugSvc hugService, userSvc userService) *Handler {
	return &Handler{hugSvc: hugSvc, userSvc: userSvc}
}

// Compile-time check that Handler satisfies the generated strict interface.
var _ StrictServerInterface = (*Handler)(nil)

// ── /users/search ──────────────────────────────────────────────────────────

// SearchUsersV2 implements substring search with optional "@username" prefix.
// When q starts with "@", display_name matches from the underlying v1 service
// are filtered out in-memory. The dataset is small enough that this keeps the
// implementation simple without adding a dedicated SQL query.
func (h *Handler) SearchUsersV2(ctx context.Context, req SearchUsersV2RequestObject) (SearchUsersV2ResponseObject, error) {
	viewerID, _ := userIDFromCtx(ctx)
	if viewerID == uuid.Nil {
		return SearchUsersV2401JSONResponse{UnauthorizedJSONResponse{Code: "UNAUTHORIZED", Message: "missing viewer"}}, nil
	}

	raw := ""
	if req.Params.Q != nil {
		raw = *req.Params.Q
	}
	query, usernameOnly := parseSearchQuery(raw)

	limit := int32(20)
	offset := int32(0)
	if req.Params.Limit != nil && *req.Params.Limit > 0 {
		limit = int32(*req.Params.Limit)
	}
	if req.Params.Offset != nil && *req.Params.Offset >= 0 {
		offset = int32(*req.Params.Offset)
	}

	users, err := h.hugSvc.SearchUsers(ctx, query, viewerID, limit, offset)
	if err != nil {
		return nil, err
	}

	if usernameOnly && query != "" {
		needle := strings.ToLower(query)
		filtered := make([]*models.User, 0, len(users))
		for _, u := range users {
			if strings.Contains(strings.ToLower(u.Username), needle) {
				filtered = append(filtered, u)
			}
		}
		users = filtered
	}

	out := make(SearchUsersV2200JSONResponse, len(users))
	for i, u := range users {
		out[i] = toUserListItem(u)
	}
	return out, nil
}

// parseSearchQuery normalises the q parameter. When q starts with "@" the
// remainder is treated as a username-only filter (usernameOnly=true).
func parseSearchQuery(raw string) (query string, usernameOnly bool) {
	if strings.HasPrefix(raw, "@") {
		return strings.TrimPrefix(raw, "@"), true
	}
	return raw, false
}

func toUserListItem(u *models.User) UserListItem {
	item := UserListItem{
		Id:                  u.ID,
		Username:            u.Username,
		Role:                u.Role,
		DisplayName:         u.DisplayName,
		Tag:                 u.Tag,
		SpecialTag:          u.SpecialTag,
		IsTelegramLinked:    u.IsTelegramLinked,
		IsRecentlyActive:    u.IsRecentlyActive,
		PromotedUntil:       u.PromotedUntil,
		PromotionMessage:    u.PromotionMessage,
		PromotionBid:        int(u.PromotionBid),
		VipRemainingSeconds: int(u.VipRemainingSeconds),
		VipCooldownUntil:    u.VipCooldownUntil,
	}
	if u.Gender != nil {
		g := Gender(*u.Gender)
		item.Gender = &g
	}
	if u.AvgResponseTime != nil {
		v := float32(*u.AvgResponseTime)
		item.AvgResponseTime = &v
	}
	return item
}

// ── /users/{usernameOrId}/profile ─────────────────────────────────────────

func (h *Handler) GetUserProfileV2(ctx context.Context, req GetUserProfileV2RequestObject) (GetUserProfileV2ResponseObject, error) {
	viewerID, _ := userIDFromCtx(ctx)
	var viewerPtr *uuid.UUID
	if viewerID != uuid.Nil {
		viewerPtr = &viewerID
	}

	targetID, err := h.resolveTarget(ctx, req.UsernameOrId)
	if err != nil {
		if errors.Is(err, errorz.ErrUserNotFound) {
			return GetUserProfileV2404JSONResponse{NotFoundJSONResponse{Code: "USER_NOT_FOUND", Message: "User not found"}}, nil
		}
		return nil, err
	}

	user, stats, bal, mutual, isBlocked, intimacy, err := h.hugSvc.GetUserProfile(ctx, targetID, viewerPtr)
	if err != nil {
		if errors.Is(err, errorz.ErrUserNotFound) {
			return GetUserProfileV2404JSONResponse{NotFoundJSONResponse{Code: "USER_NOT_FOUND", Message: "User not found"}}, nil
		}
		return nil, err
	}

	resp := GetUserProfileV2200JSONResponse{
		Id:           user.ID,
		Username:     user.Username,
		Role:         user.Role,
		DisplayName:  user.DisplayName,
		Tag:          user.Tag,
		SpecialTag:   user.SpecialTag,
		HugsGiven:    int(stats.HugsGiven),
		HugsReceived: int(stats.HugsReceived),
		TotalHugs:    int(stats.TotalHugs),
		Rank:         models.GetRank(stats.TotalHugs, user.Gender),
		CaptchaType:  user.CaptchaType,
	}
	if user.Gender != nil {
		g := Gender(*user.Gender)
		resp.Gender = &g
	}
	if user.CaptchaCooldownUntil != nil {
		resp.CaptchaCooldownUntil = user.CaptchaCooldownUntil
	}
	if bal != nil {
		amt := int(bal.Amount)
		resp.Balance = &amt
	}
	if mutual != nil {
		tot := int(mutual.Total)
		giv := int(mutual.Given)
		rec := int(mutual.Received)
		resp.MutualTotal = &tot
		resp.MutualGiven = &giv
		resp.MutualReceived = &rec
	}
	if viewerPtr != nil && *viewerPtr != targetID {
		blocked := isBlocked
		resp.IsBlocked = &blocked
	}
	if intimacy != nil {
		hugTypes := make([]HugType, len(intimacy.AvailableHugTypes))
		for i, ht := range intimacy.AvailableHugTypes {
			hugTypes[i] = HugType(ht)
		}
		resp.Intimacy = &IntimacyInfo{
			RawScore:             intimacy.RawScore,
			Tier:                 intimacy.Tier,
			TierName:             intimacy.TierName,
			NextTierAt:           intimacy.NextTierAt,
			CooldownReductionPct: intimacy.CooldownReductionPct,
			AvailableHugTypes:    hugTypes,
			BonusCoins:           intimacy.BonusCoins,
		}
	}
	return resp, nil
}

// resolveTarget accepts a UUID, a username, or an "@username" string and
// returns the target user's UUID.
func (h *Handler) resolveTarget(ctx context.Context, raw string) (uuid.UUID, error) {
	if id, err := uuid.Parse(raw); err == nil {
		return id, nil
	}
	username := strings.TrimPrefix(raw, "@")
	if username == "" {
		return uuid.Nil, errorz.ErrUserNotFound
	}
	u, err := h.userSvc.GetByUsername(ctx, username)
	if err != nil {
		return uuid.Nil, err
	}
	return u.ID, nil
}

// ── /daily-reward/status ───────────────────────────────────────────────────

func (h *Handler) GetDailyRewardStatus(ctx context.Context, _ GetDailyRewardStatusRequestObject) (GetDailyRewardStatusResponseObject, error) {
	userID, _ := userIDFromCtx(ctx)
	if userID == uuid.Nil {
		return GetDailyRewardStatus401JSONResponse{UnauthorizedJSONResponse{Code: "UNAUTHORIZED", Message: "missing user"}}, nil
	}

	canClaim, nextClaimAt, streak, lastClaimed, err := h.hugSvc.GetDailyRewardStatus(ctx, userID)
	if err != nil {
		return nil, err
	}

	return GetDailyRewardStatus200JSONResponse{
		CanClaim:      canClaim,
		NextClaimAt:   nextClaimAt,
		StreakDays:    int(streak),
		LastClaimedAt: lastClaimed,
	}, nil
}
