// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
WITH deactivated AS (
    UPDATE announcements SET active = FALSE WHERE active = TRUE
)
INSERT INTO announcements (message, created_by)
VALUES ($1::text, $2::uuid)
RETURNING id, message, created_at, created_by, active
`

type CreateAnnouncementParams struct {
	Message   string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement, arg.Message, arg.CreatedBy)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Active,
	)
	return i, err
}

const deactivateAnnouncement = `-- name: DeactivateAnnouncement :exec
UPDATE announcements SET active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateAnnouncement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAnnouncement, id)
	return err
}

const dismissAnnouncement = `-- name: DismissAnnouncement :exec
INSERT INTO announcement_dismissals (announcement_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type DismissAnnouncementParams struct {
	AnnouncementID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) DismissAnnouncement(ctx context.Context, arg DismissAnnouncementParams) error {
	_, err := q.db.Exec(ctx, dismissAnnouncement, arg.AnnouncementID, arg.UserID)
	return err
}

const getActiveAnnouncement = `-- name: GetActiveAnnouncement :one
SELECT id, message, created_at, created_by, active
FROM announcements
WHERE active = TRUE
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveAnnouncement(ctx context.Context) (Announcement, error) {
	row := q.db.QueryRow(ctx, getActiveAnnouncement)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Active,
	)
	return i, err
}

const getActiveAnnouncementForUser = `-- name: GetActiveAnnouncementForUser :one
SELECT a.id, a.message, a.created_at, a.created_by
FROM announcements a
WHERE a.active = TRUE
  AND NOT EXISTS (
    SELECT 1 FROM announcement_dismissals ad
    WHERE ad.announcement_id = a.id AND ad.user_id = $1::uuid
  )
ORDER BY a.created_at DESC
LIMIT 1
`

type GetActiveAnnouncementForUserRow struct {
	ID        uuid.UUID
	Message   string
	CreatedAt pgtype.Timestamptz
	CreatedBy uuid.UUID
}

func (q *Queries) GetActiveAnnouncementForUser(ctx context.Context, userID uuid.UUID) (GetActiveAnnouncementForUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveAnnouncementForUser, userID)
	var i GetActiveAnnouncementForUserRow
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
