// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const addBalance = `-- name: AddBalance :one
INSERT INTO balances (user_id, amount, updated_at)
VALUES ($1, $2::int, now())
ON CONFLICT (user_id)
DO UPDATE SET amount = balances.amount + $2::int, updated_at = now()
RETURNING user_id, amount, updated_at
`

type AddBalanceParams struct {
	UserID uuid.UUID
	Delta  int32
}

func (q *Queries) AddBalance(ctx context.Context, arg AddBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, addBalance, arg.UserID, arg.Delta)
	var i Balance
	err := row.Scan(&i.UserID, &i.Amount, &i.UpdatedAt)
	return i, err
}

const adminSetBalance = `-- name: AdminSetBalance :one
INSERT INTO balances (user_id, amount, updated_at)
VALUES ($1, $2::int, now())
ON CONFLICT (user_id)
DO UPDATE SET amount = $2::int, updated_at = now()
RETURNING user_id, amount, updated_at
`

type AdminSetBalanceParams struct {
	UserID uuid.UUID
	Amount int32
}

func (q *Queries) AdminSetBalance(ctx context.Context, arg AdminSetBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, adminSetBalance, arg.UserID, arg.Amount)
	var i Balance
	err := row.Scan(&i.UserID, &i.Amount, &i.UpdatedAt)
	return i, err
}

const createBalance = `-- name: CreateBalance :one
INSERT INTO balances (user_id, amount)
VALUES ($1, $2)
RETURNING user_id, amount, updated_at
`

type CreateBalanceParams struct {
	UserID uuid.UUID
	Amount int32
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, createBalance, arg.UserID, arg.Amount)
	var i Balance
	err := row.Scan(&i.UserID, &i.Amount, &i.UpdatedAt)
	return i, err
}

const deductBalance = `-- name: DeductBalance :one
UPDATE balances
SET amount = amount - $2::int, updated_at = now()
WHERE user_id = $1 AND amount >= $2::int
RETURNING user_id, amount, updated_at
`

type DeductBalanceParams struct {
	UserID uuid.UUID
	Delta  int32
}

func (q *Queries) DeductBalance(ctx context.Context, arg DeductBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, deductBalance, arg.UserID, arg.Delta)
	var i Balance
	err := row.Scan(&i.UserID, &i.Amount, &i.UpdatedAt)
	return i, err
}

const ensureBalance = `-- name: EnsureBalance :one
INSERT INTO balances (user_id, amount)
VALUES ($1, 0)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, amount, updated_at
`

func (q *Queries) EnsureBalance(ctx context.Context, userID uuid.UUID) (Balance, error) {
	row := q.db.QueryRow(ctx, ensureBalance, userID)
	var i Balance
	err := row.Scan(&i.UserID, &i.Amount, &i.UpdatedAt)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT user_id, amount, updated_at
FROM balances
WHERE user_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, userID uuid.UUID) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var i Balance
	err := row.Scan(&i.UserID, &i.Amount, &i.UpdatedAt)
	return i, err
}
