// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: block.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO user_blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const getBlockedUsers = `-- name: GetBlockedUsers :many
SELECT u.id, u.username, u.gender, u.display_name, u.tag, u.special_tag, ub.created_at
FROM user_blocks ub
JOIN users u ON u.id = ub.blocked_id
WHERE ub.blocker_id = $1
ORDER BY ub.created_at DESC
`

type GetBlockedUsersRow struct {
	ID          uuid.UUID
	Username    string
	Gender      pgtype.Text
	DisplayName pgtype.Text
	Tag         pgtype.Text
	SpecialTag  pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetBlockedUsers(ctx context.Context, blockerID uuid.UUID) ([]GetBlockedUsersRow, error) {
	rows, err := q.db.Query(ctx, getBlockedUsers, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlockedUsersRow
	for rows.Next() {
		var i GetBlockedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Gender,
			&i.DisplayName,
			&i.Tag,
			&i.SpecialTag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isBlockedByEither = `-- name: IsBlockedByEither :one
SELECT EXISTS(
    SELECT 1 FROM user_blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
       OR (blocker_id = $2 AND blocked_id = $1)
) AS is_blocked
`

type IsBlockedByEitherParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) IsBlockedByEither(ctx context.Context, arg IsBlockedByEitherParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedByEither, arg.BlockerID, arg.BlockedID)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM user_blocks
WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}
