// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: casino.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCasinoCaptcha = `-- name: CreateCasinoCaptcha :one
INSERT INTO casino_captchas (user_id, expires_at)
VALUES ($1, $2)
RETURNING id, user_id, passed, expires_at, created_at
`

type CreateCasinoCaptchaParams struct {
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateCasinoCaptcha(ctx context.Context, arg CreateCasinoCaptchaParams) (CasinoCaptcha, error) {
	row := q.db.QueryRow(ctx, createCasinoCaptcha, arg.UserID, arg.ExpiresAt)
	var i CasinoCaptcha
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Passed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCasinoCaptcha = `-- name: DeleteCasinoCaptcha :exec
DELETE FROM casino_captchas WHERE id = $1
`

func (q *Queries) DeleteCasinoCaptcha(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCasinoCaptcha, id)
	return err
}

const getCasinoCaptcha = `-- name: GetCasinoCaptcha :one
SELECT id, user_id, passed, expires_at, created_at FROM casino_captchas WHERE id = $1
`

func (q *Queries) GetCasinoCaptcha(ctx context.Context, id uuid.UUID) (CasinoCaptcha, error) {
	row := q.db.QueryRow(ctx, getCasinoCaptcha, id)
	var i CasinoCaptcha
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Passed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markCasinoPassed = `-- name: MarkCasinoPassed :one
UPDATE casino_captchas
SET passed = TRUE
WHERE id = $1
RETURNING id, user_id, passed, expires_at, created_at
`

func (q *Queries) MarkCasinoPassed(ctx context.Context, id uuid.UUID) (CasinoCaptcha, error) {
	row := q.db.QueryRow(ctx, markCasinoPassed, id)
	var i CasinoCaptcha
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Passed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
