// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cooldown.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCooldown = `-- name: GetCooldown :one
SELECT user_a_id, user_b_id, last_hug_at, cooldown_seconds, decline_cooldown_until
FROM hug_cooldowns
WHERE user_a_id = LEAST($1::UUID, $2::UUID)
  AND user_b_id = GREATEST($1::UUID, $2::UUID)
`

type GetCooldownParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
}

func (q *Queries) GetCooldown(ctx context.Context, arg GetCooldownParams) (HugCooldown, error) {
	row := q.db.QueryRow(ctx, getCooldown, arg.Column1, arg.Column2)
	var i HugCooldown
	err := row.Scan(
		&i.UserAID,
		&i.UserBID,
		&i.LastHugAt,
		&i.CooldownSeconds,
		&i.DeclineCooldownUntil,
	)
	return i, err
}

const reduceCooldown = `-- name: ReduceCooldown :one
UPDATE hug_cooldowns
SET cooldown_seconds = GREATEST(cooldown_seconds - $3::INTEGER, 300)
WHERE user_a_id = LEAST($1::UUID, $2::UUID)
  AND user_b_id = GREATEST($1::UUID, $2::UUID)
RETURNING user_a_id, user_b_id, last_hug_at, cooldown_seconds, decline_cooldown_until
`

type ReduceCooldownParams struct {
	Column1   uuid.UUID
	Column2   uuid.UUID
	Reduction int32
}

func (q *Queries) ReduceCooldown(ctx context.Context, arg ReduceCooldownParams) (HugCooldown, error) {
	row := q.db.QueryRow(ctx, reduceCooldown, arg.Column1, arg.Column2, arg.Reduction)
	var i HugCooldown
	err := row.Scan(
		&i.UserAID,
		&i.UserBID,
		&i.LastHugAt,
		&i.CooldownSeconds,
		&i.DeclineCooldownUntil,
	)
	return i, err
}

const setDeclineCooldown = `-- name: SetDeclineCooldown :exec
INSERT INTO hug_cooldowns (user_a_id, user_b_id, decline_cooldown_until, cooldown_seconds, last_hug_at)
VALUES (LEAST($1::UUID, $2::UUID), GREATEST($1::UUID, $2::UUID), $3, 3600, '2000-01-01'::timestamptz)
ON CONFLICT (user_a_id, user_b_id)
DO UPDATE SET decline_cooldown_until = $3
`

type SetDeclineCooldownParams struct {
	Column1              uuid.UUID
	Column2              uuid.UUID
	DeclineCooldownUntil pgtype.Timestamptz
}

func (q *Queries) SetDeclineCooldown(ctx context.Context, arg SetDeclineCooldownParams) error {
	_, err := q.db.Exec(ctx, setDeclineCooldown, arg.Column1, arg.Column2, arg.DeclineCooldownUntil)
	return err
}

const setSudokuPenaltyCooldown = `-- name: SetSudokuPenaltyCooldown :exec
INSERT INTO hug_cooldowns (user_a_id, user_b_id, decline_cooldown_until, cooldown_seconds, last_hug_at)
VALUES (LEAST($1::UUID, $2::UUID), GREATEST($1::UUID, $2::UUID), $3, 3600, '2000-01-01'::timestamptz)
ON CONFLICT (user_a_id, user_b_id)
DO UPDATE SET decline_cooldown_until = $3
`

type SetSudokuPenaltyCooldownParams struct {
	Column1              uuid.UUID
	Column2              uuid.UUID
	DeclineCooldownUntil pgtype.Timestamptz
}

func (q *Queries) SetSudokuPenaltyCooldown(ctx context.Context, arg SetSudokuPenaltyCooldownParams) error {
	_, err := q.db.Exec(ctx, setSudokuPenaltyCooldown, arg.Column1, arg.Column2, arg.DeclineCooldownUntil)
	return err
}

const upsertCooldown = `-- name: UpsertCooldown :one
INSERT INTO hug_cooldowns (user_a_id, user_b_id, cooldown_seconds)
VALUES (LEAST($1::UUID, $2::UUID), GREATEST($1::UUID, $2::UUID), $3)
ON CONFLICT (user_a_id, user_b_id)
DO UPDATE SET last_hug_at = now()
RETURNING user_a_id, user_b_id, last_hug_at, cooldown_seconds, decline_cooldown_until
`

type UpsertCooldownParams struct {
	Column1         uuid.UUID
	Column2         uuid.UUID
	CooldownSeconds int32
}

func (q *Queries) UpsertCooldown(ctx context.Context, arg UpsertCooldownParams) (HugCooldown, error) {
	row := q.db.QueryRow(ctx, upsertCooldown, arg.Column1, arg.Column2, arg.CooldownSeconds)
	var i HugCooldown
	err := row.Scan(
		&i.UserAID,
		&i.UserBID,
		&i.LastHugAt,
		&i.CooldownSeconds,
		&i.DeclineCooldownUntil,
	)
	return i, err
}
