// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_reward.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const claimDailyReward = `-- name: ClaimDailyReward :one
INSERT INTO daily_rewards (user_id, last_claimed_at, streak_days)
VALUES ($1, now(), 1)
ON CONFLICT (user_id)
DO UPDATE SET
    streak_days = CASE
        WHEN daily_rewards.last_claimed_at::date = (now() - interval '1 day')::date
        THEN daily_rewards.streak_days + 1
        WHEN daily_rewards.last_claimed_at::date = now()::date
        THEN daily_rewards.streak_days  -- already claimed today, no change
        ELSE 1  -- streak reset
    END,
    last_claimed_at = CASE
        WHEN daily_rewards.last_claimed_at::date = now()::date
        THEN daily_rewards.last_claimed_at  -- don't update if already claimed today
        ELSE now()
    END
RETURNING user_id, last_claimed_at, streak_days
`

func (q *Queries) ClaimDailyReward(ctx context.Context, userID uuid.UUID) (DailyReward, error) {
	row := q.db.QueryRow(ctx, claimDailyReward, userID)
	var i DailyReward
	err := row.Scan(&i.UserID, &i.LastClaimedAt, &i.StreakDays)
	return i, err
}

const getDailyReward = `-- name: GetDailyReward :one
SELECT user_id, last_claimed_at, streak_days
FROM daily_rewards
WHERE user_id = $1
`

func (q *Queries) GetDailyReward(ctx context.Context, userID uuid.UUID) (DailyReward, error) {
	row := q.db.QueryRow(ctx, getDailyReward, userID)
	var i DailyReward
	err := row.Scan(&i.UserID, &i.LastClaimedAt, &i.StreakDays)
	return i, err
}
