// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hug.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptHug = `-- name: AcceptHug :one
UPDATE hugs SET status = 'completed', accepted_at = now(), streak_tier = $3
WHERE id = $1 AND receiver_id = $2 AND status = 'pending'
RETURNING id, giver_id, receiver_id, created_at, status, accepted_at, hug_type, comment, streak_tier
`

type AcceptHugParams struct {
	ID         uuid.UUID
	ReceiverID uuid.UUID
	StreakTier string
}

func (q *Queries) AcceptHug(ctx context.Context, arg AcceptHugParams) (Hug, error) {
	row := q.db.QueryRow(ctx, acceptHug, arg.ID, arg.ReceiverID, arg.StreakTier)
	var i Hug
	err := row.Scan(
		&i.ID,
		&i.GiverID,
		&i.ReceiverID,
		&i.CreatedAt,
		&i.Status,
		&i.AcceptedAt,
		&i.HugType,
		&i.Comment,
		&i.StreakTier,
	)
	return i, err
}

const cancelHug = `-- name: CancelHug :one
UPDATE hugs SET status = 'cancelled'
WHERE id = $1 AND giver_id = $2 AND status = 'pending'
RETURNING id, giver_id, receiver_id, created_at, status, accepted_at, hug_type, comment, streak_tier
`

type CancelHugParams struct {
	ID      uuid.UUID
	GiverID uuid.UUID
}

func (q *Queries) CancelHug(ctx context.Context, arg CancelHugParams) (Hug, error) {
	row := q.db.QueryRow(ctx, cancelHug, arg.ID, arg.GiverID)
	var i Hug
	err := row.Scan(
		&i.ID,
		&i.GiverID,
		&i.ReceiverID,
		&i.CreatedAt,
		&i.Status,
		&i.AcceptedAt,
		&i.HugType,
		&i.Comment,
		&i.StreakTier,
	)
	return i, err
}

const checkSuggestEligibility = `-- name: CheckSuggestEligibility :one
SELECT
    (SELECT COUNT(*) FROM hugs
     WHERE giver_id = $1::uuid
       AND status = 'pending'
       AND created_at > now() - INTERVAL '24 hours'
    )::int AS outgoing_count,
    EXISTS(
        SELECT 1 FROM hugs
        WHERE giver_id = $1::uuid
          AND receiver_id = $2::uuid
          AND status = 'pending'
          AND created_at > now() - INTERVAL '24 hours'
    ) AS pair_pending,
    EXISTS(
        SELECT 1 FROM hugs
        WHERE giver_id = $2::uuid
          AND receiver_id = $1::uuid
          AND status = 'pending'
          AND created_at > now() - INTERVAL '24 hours'
    ) AS reverse_pending
`

type CheckSuggestEligibilityParams struct {
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
}

type CheckSuggestEligibilityRow struct {
	OutgoingCount  int32
	PairPending    bool
	ReversePending bool
}

func (q *Queries) CheckSuggestEligibility(ctx context.Context, arg CheckSuggestEligibilityParams) (CheckSuggestEligibilityRow, error) {
	row := q.db.QueryRow(ctx, checkSuggestEligibility, arg.GiverID, arg.ReceiverID)
	var i CheckSuggestEligibilityRow
	err := row.Scan(&i.OutgoingCount, &i.PairPending, &i.ReversePending)
	return i, err
}

const countHugsGiven = `-- name: CountHugsGiven :one
SELECT COUNT(*)
FROM hugs
WHERE giver_id = $1
  AND status = 'completed'
`

func (q *Queries) CountHugsGiven(ctx context.Context, giverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHugsGiven, giverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHugsReceived = `-- name: CountHugsReceived :one
SELECT COUNT(*)
FROM hugs
WHERE receiver_id = $1
  AND status = 'completed'
`

func (q *Queries) CountHugsReceived(ctx context.Context, receiverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHugsReceived, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMutualHugs = `-- name: CountMutualHugs :one
SELECT
    COUNT(*)::bigint AS mutual_total,
    COUNT(*) FILTER (WHERE giver_id = $1 AND receiver_id = $2)::bigint AS mutual_given,
    COUNT(*) FILTER (WHERE giver_id = $2 AND receiver_id = $1)::bigint AS mutual_received
FROM hugs
WHERE ((giver_id = $1 AND receiver_id = $2)
   OR (giver_id = $2 AND receiver_id = $1))
  AND status = 'completed'
`

type CountMutualHugsParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

type CountMutualHugsRow struct {
	MutualTotal    int64
	MutualGiven    int64
	MutualReceived int64
}

func (q *Queries) CountMutualHugs(ctx context.Context, arg CountMutualHugsParams) (CountMutualHugsRow, error) {
	row := q.db.QueryRow(ctx, countMutualHugs, arg.UserA, arg.UserB)
	var i CountMutualHugsRow
	err := row.Scan(&i.MutualTotal, &i.MutualGiven, &i.MutualReceived)
	return i, err
}

const countPendingHugsForUser = `-- name: CountPendingHugsForUser :one
SELECT COUNT(*) FROM hugs
WHERE receiver_id = $1
  AND status = 'pending'
  AND created_at > now() - INTERVAL '24 hours'
`

func (q *Queries) CountPendingHugsForUser(ctx context.Context, receiverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingHugsForUser, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const declineHug = `-- name: DeclineHug :one
UPDATE hugs SET status = 'declined'
WHERE id = $1 AND receiver_id = $2 AND status = 'pending'
RETURNING id, giver_id, receiver_id, created_at, status, accepted_at, hug_type, comment, streak_tier
`

type DeclineHugParams struct {
	ID         uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) DeclineHug(ctx context.Context, arg DeclineHugParams) (Hug, error) {
	row := q.db.QueryRow(ctx, declineHug, arg.ID, arg.ReceiverID)
	var i Hug
	err := row.Scan(
		&i.ID,
		&i.GiverID,
		&i.ReceiverID,
		&i.CreatedAt,
		&i.Status,
		&i.AcceptedAt,
		&i.HugType,
		&i.Comment,
		&i.StreakTier,
	)
	return i, err
}

const expirePendingHugs = `-- name: ExpirePendingHugs :exec
UPDATE hugs SET status = 'expired'
WHERE status = 'pending'
  AND created_at <= now() - INTERVAL '24 hours'
`

func (q *Queries) ExpirePendingHugs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expirePendingHugs)
	return err
}

const getHugActivity = `-- name: GetHugActivity :many
SELECT
    bucket::timestamptz AS bucket_time,
    COALESCE(COUNT(h.id), 0)::bigint AS hug_count
FROM generate_series(
    DATE_TRUNC('hour', NOW() - INTERVAL '23 hours'),
    DATE_TRUNC('hour', NOW()),
    '1 hour'::interval
) AS bucket
LEFT JOIN hugs h
    ON h.created_at >= bucket
   AND h.created_at < bucket + '1 hour'::interval
   AND h.status = 'completed'
GROUP BY bucket
ORDER BY bucket
`

type GetHugActivityRow struct {
	BucketTime pgtype.Timestamptz
	HugCount   int64
}

func (q *Queries) GetHugActivity(ctx context.Context) ([]GetHugActivityRow, error) {
	rows, err := q.db.Query(ctx, getHugActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHugActivityRow
	for rows.Next() {
		var i GetHugActivityRow
		if err := rows.Scan(&i.BucketTime, &i.HugCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugByID = `-- name: GetHugByID :one
SELECT id, giver_id, receiver_id, status, hug_type, created_at, accepted_at, comment, streak_tier
FROM hugs
WHERE id = $1
`

type GetHugByIDRow struct {
	ID         uuid.UUID
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
	Status     string
	HugType    string
	CreatedAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	Comment    pgtype.Text
	StreakTier string
}

func (q *Queries) GetHugByID(ctx context.Context, id uuid.UUID) (GetHugByIDRow, error) {
	row := q.db.QueryRow(ctx, getHugByID, id)
	var i GetHugByIDRow
	err := row.Scan(
		&i.ID,
		&i.GiverID,
		&i.ReceiverID,
		&i.Status,
		&i.HugType,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.Comment,
		&i.StreakTier,
	)
	return i, err
}

const getHugDetail = `-- name: GetHugDetail :one
SELECT
    h.id,
    h.giver_id,
    h.receiver_id,
    h.status,
    h.hug_type,
    h.comment,
    h.streak_tier,
    h.created_at,
    h.accepted_at,
    g.username AS giver_username,
    g.gender AS giver_gender,
    g.display_name AS giver_display_name,
    r.username AS receiver_username,
    r.gender AS receiver_gender,
    r.display_name AS receiver_display_name
FROM hugs h
JOIN users g ON g.id = h.giver_id
JOIN users r ON r.id = h.receiver_id
WHERE h.id = $1
`

type GetHugDetailRow struct {
	ID                  uuid.UUID
	GiverID             uuid.UUID
	ReceiverID          uuid.UUID
	Status              string
	HugType             string
	Comment             pgtype.Text
	StreakTier          string
	CreatedAt           pgtype.Timestamptz
	AcceptedAt          pgtype.Timestamptz
	GiverUsername       string
	GiverGender         pgtype.Text
	GiverDisplayName    pgtype.Text
	ReceiverUsername    string
	ReceiverGender      pgtype.Text
	ReceiverDisplayName pgtype.Text
}

func (q *Queries) GetHugDetail(ctx context.Context, id uuid.UUID) (GetHugDetailRow, error) {
	row := q.db.QueryRow(ctx, getHugDetail, id)
	var i GetHugDetailRow
	err := row.Scan(
		&i.ID,
		&i.GiverID,
		&i.ReceiverID,
		&i.Status,
		&i.HugType,
		&i.Comment,
		&i.StreakTier,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.GiverUsername,
		&i.GiverGender,
		&i.GiverDisplayName,
		&i.ReceiverUsername,
		&i.ReceiverGender,
		&i.ReceiverDisplayName,
	)
	return i, err
}

const getOutgoingPendingHugs = `-- name: GetOutgoingPendingHugs :many
SELECT h.id, h.giver_id, h.receiver_id, h.status, h.created_at, h.accepted_at,
       h.hug_type, h.comment,
       r.username AS receiver_username, r.gender AS receiver_gender,
       r.display_name AS receiver_display_name
FROM hugs h
JOIN users r ON r.id = h.receiver_id
WHERE h.giver_id = $1
  AND h.status = 'pending'
  AND h.created_at > now() - INTERVAL '24 hours'
ORDER BY h.created_at DESC
`

type GetOutgoingPendingHugsRow struct {
	ID                  uuid.UUID
	GiverID             uuid.UUID
	ReceiverID          uuid.UUID
	Status              string
	CreatedAt           pgtype.Timestamptz
	AcceptedAt          pgtype.Timestamptz
	HugType             string
	Comment             pgtype.Text
	ReceiverUsername    string
	ReceiverGender      pgtype.Text
	ReceiverDisplayName pgtype.Text
}

func (q *Queries) GetOutgoingPendingHugs(ctx context.Context, giverID uuid.UUID) ([]GetOutgoingPendingHugsRow, error) {
	rows, err := q.db.Query(ctx, getOutgoingPendingHugs, giverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutgoingPendingHugsRow
	for rows.Next() {
		var i GetOutgoingPendingHugsRow
		if err := rows.Scan(
			&i.ID,
			&i.GiverID,
			&i.ReceiverID,
			&i.Status,
			&i.CreatedAt,
			&i.AcceptedAt,
			&i.HugType,
			&i.Comment,
			&i.ReceiverUsername,
			&i.ReceiverGender,
			&i.ReceiverDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingHugsForUser = `-- name: GetPendingHugsForUser :many
SELECT h.id, h.giver_id, h.receiver_id, h.status, h.created_at, h.accepted_at,
       h.hug_type, h.comment,
       g.username AS giver_username, g.gender AS giver_gender,
       g.display_name AS giver_display_name
FROM hugs h
JOIN users g ON g.id = h.giver_id
WHERE h.receiver_id = $1
  AND h.status = 'pending'
  AND h.created_at > now() - INTERVAL '24 hours'
ORDER BY h.created_at DESC
`

type GetPendingHugsForUserRow struct {
	ID               uuid.UUID
	GiverID          uuid.UUID
	ReceiverID       uuid.UUID
	Status           string
	CreatedAt        pgtype.Timestamptz
	AcceptedAt       pgtype.Timestamptz
	HugType          string
	Comment          pgtype.Text
	GiverUsername    string
	GiverGender      pgtype.Text
	GiverDisplayName pgtype.Text
}

func (q *Queries) GetPendingHugsForUser(ctx context.Context, receiverID uuid.UUID) ([]GetPendingHugsForUserRow, error) {
	rows, err := q.db.Query(ctx, getPendingHugsForUser, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingHugsForUserRow
	for rows.Next() {
		var i GetPendingHugsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GiverID,
			&i.ReceiverID,
			&i.Status,
			&i.CreatedAt,
			&i.AcceptedAt,
			&i.HugType,
			&i.Comment,
			&i.GiverUsername,
			&i.GiverGender,
			&i.GiverDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasOutgoingPendingHug = `-- name: HasOutgoingPendingHug :one
SELECT EXISTS(
    SELECT 1 FROM hugs
    WHERE giver_id = $1
      AND status = 'pending'
      AND created_at > now() - INTERVAL '24 hours'
) AS has_pending
`

func (q *Queries) HasOutgoingPendingHug(ctx context.Context, giverID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasOutgoingPendingHug, giverID)
	var has_pending bool
	err := row.Scan(&has_pending)
	return has_pending, err
}

const hasPendingHugForPair = `-- name: HasPendingHugForPair :one
SELECT EXISTS(
    SELECT 1 FROM hugs
    WHERE giver_id = $1
      AND receiver_id = $2
      AND status = 'pending'
      AND created_at > now() - INTERVAL '24 hours'
) AS has_pending
`

type HasPendingHugForPairParams struct {
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) HasPendingHugForPair(ctx context.Context, arg HasPendingHugForPairParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingHugForPair, arg.GiverID, arg.ReceiverID)
	var has_pending bool
	err := row.Scan(&has_pending)
	return has_pending, err
}

const insertHug = `-- name: InsertHug :one
INSERT INTO hugs (giver_id, receiver_id, status, hug_type, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, giver_id, receiver_id, created_at, status, accepted_at, hug_type, comment, streak_tier
`

type InsertHugParams struct {
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
	Status     string
	HugType    string
	Comment    pgtype.Text
}

func (q *Queries) InsertHug(ctx context.Context, arg InsertHugParams) (Hug, error) {
	row := q.db.QueryRow(ctx, insertHug,
		arg.GiverID,
		arg.ReceiverID,
		arg.Status,
		arg.HugType,
		arg.Comment,
	)
	var i Hug
	err := row.Scan(
		&i.ID,
		&i.GiverID,
		&i.ReceiverID,
		&i.CreatedAt,
		&i.Status,
		&i.AcceptedAt,
		&i.HugType,
		&i.Comment,
		&i.StreakTier,
	)
	return i, err
}

const listHugsByUser = `-- name: ListHugsByUser :many
SELECT
    h.id,
    h.giver_id,
    h.receiver_id,
    COALESCE(h.accepted_at, h.created_at) AS created_at,
    h.hug_type,
    (h.comment IS NOT NULL)::bool AS has_comment,
    h.streak_tier,
    g.username AS giver_username,
    r.username AS receiver_username,
    g.gender AS giver_gender,
    g.display_name AS giver_display_name,
    r.display_name AS receiver_display_name
FROM hugs h
JOIN users g ON g.id = h.giver_id
JOIN users r ON r.id = h.receiver_id
WHERE (h.giver_id = $1::uuid OR h.receiver_id = $1::uuid)
  AND h.status = 'completed'
ORDER BY COALESCE(h.accepted_at, h.created_at) DESC
LIMIT $3::int OFFSET $2::int
`

type ListHugsByUserParams struct {
	UserID uuid.UUID
	Off    int32
	Lim    int32
}

type ListHugsByUserRow struct {
	ID                  uuid.UUID
	GiverID             uuid.UUID
	ReceiverID          uuid.UUID
	CreatedAt           pgtype.Timestamptz
	HugType             string
	HasComment          bool
	StreakTier          string
	GiverUsername       string
	ReceiverUsername    string
	GiverGender         pgtype.Text
	GiverDisplayName    pgtype.Text
	ReceiverDisplayName pgtype.Text
}

func (q *Queries) ListHugsByUser(ctx context.Context, arg ListHugsByUserParams) ([]ListHugsByUserRow, error) {
	rows, err := q.db.Query(ctx, listHugsByUser, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHugsByUserRow
	for rows.Next() {
		var i ListHugsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GiverID,
			&i.ReceiverID,
			&i.CreatedAt,
			&i.HugType,
			&i.HasComment,
			&i.StreakTier,
			&i.GiverUsername,
			&i.ReceiverUsername,
			&i.GiverGender,
			&i.GiverDisplayName,
			&i.ReceiverDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
