// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intimacy.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyIntimacyDecay = `-- name: ApplyIntimacyDecay :exec
UPDATE pair_intimacy
SET raw_score = GREATEST(
        raw_score - FLOOR(EXTRACT(EPOCH FROM (NOW() - last_decay_at)) / 259200)::int,
        0
    ),
    last_decay_at = NOW()
WHERE last_decay_at < NOW() - INTERVAL '3 days'
  AND raw_score > 0
`

func (q *Queries) ApplyIntimacyDecay(ctx context.Context) error {
	_, err := q.db.Exec(ctx, applyIntimacyDecay)
	return err
}

const getIntimacyLeaderboard = `-- name: GetIntimacyLeaderboard :many
SELECT
    pi.user_a_id,
    pi.user_b_id,
    pi.raw_score,
    ua.username AS user_a_username,
    ua.display_name AS user_a_display_name,
    ub.username AS user_b_username,
    ub.display_name AS user_b_display_name
FROM pair_intimacy pi
JOIN users ua ON ua.id = pi.user_a_id
JOIN users ub ON ub.id = pi.user_b_id
WHERE pi.raw_score > 0
ORDER BY pi.raw_score DESC
LIMIT $2 OFFSET $1
`

type GetIntimacyLeaderboardParams struct {
	Off int32
	Lim int32
}

type GetIntimacyLeaderboardRow struct {
	UserAID          uuid.UUID
	UserBID          uuid.UUID
	RawScore         int32
	UserAUsername    string
	UserADisplayName pgtype.Text
	UserBUsername    string
	UserBDisplayName pgtype.Text
}

func (q *Queries) GetIntimacyLeaderboard(ctx context.Context, arg GetIntimacyLeaderboardParams) ([]GetIntimacyLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getIntimacyLeaderboard, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIntimacyLeaderboardRow
	for rows.Next() {
		var i GetIntimacyLeaderboardRow
		if err := rows.Scan(
			&i.UserAID,
			&i.UserBID,
			&i.RawScore,
			&i.UserAUsername,
			&i.UserADisplayName,
			&i.UserBUsername,
			&i.UserBDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPairIntimacy = `-- name: GetPairIntimacy :one
SELECT user_a_id, user_b_id, raw_score, last_hug_at, last_decay_at
FROM pair_intimacy
WHERE user_a_id = LEAST($1::uuid, $2::uuid)
  AND user_b_id = GREATEST($1::uuid, $2::uuid)
`

type GetPairIntimacyParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) GetPairIntimacy(ctx context.Context, arg GetPairIntimacyParams) (PairIntimacy, error) {
	row := q.db.QueryRow(ctx, getPairIntimacy, arg.UserA, arg.UserB)
	var i PairIntimacy
	err := row.Scan(
		&i.UserAID,
		&i.UserBID,
		&i.RawScore,
		&i.LastHugAt,
		&i.LastDecayAt,
	)
	return i, err
}

const getUserConnections = `-- name: GetUserConnections :many
SELECT
    pi.user_a_id,
    pi.user_b_id,
    pi.raw_score,
    pi.last_hug_at,
    pi.last_decay_at,
    u.username,
    u.gender,
    u.display_name
FROM pair_intimacy pi
JOIN users u ON u.id = CASE
    WHEN pi.user_a_id = $1::uuid THEN pi.user_b_id
    ELSE pi.user_a_id
END
WHERE (pi.user_a_id = $1::uuid OR pi.user_b_id = $1::uuid)
  AND pi.raw_score > 0
ORDER BY pi.raw_score DESC
LIMIT $3 OFFSET $2
`

type GetUserConnectionsParams struct {
	UserID uuid.UUID
	Off    int32
	Lim    int32
}

type GetUserConnectionsRow struct {
	UserAID     uuid.UUID
	UserBID     uuid.UUID
	RawScore    int32
	LastHugAt   pgtype.Timestamptz
	LastDecayAt pgtype.Timestamptz
	Username    string
	Gender      pgtype.Text
	DisplayName pgtype.Text
}

func (q *Queries) GetUserConnections(ctx context.Context, arg GetUserConnectionsParams) ([]GetUserConnectionsRow, error) {
	rows, err := q.db.Query(ctx, getUserConnections, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConnectionsRow
	for rows.Next() {
		var i GetUserConnectionsRow
		if err := rows.Scan(
			&i.UserAID,
			&i.UserBID,
			&i.RawScore,
			&i.LastHugAt,
			&i.LastDecayAt,
			&i.Username,
			&i.Gender,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPairIntimacy = `-- name: UpsertPairIntimacy :one
INSERT INTO pair_intimacy (user_a_id, user_b_id, raw_score, last_hug_at, last_decay_at)
VALUES (
    LEAST($1::uuid, $2::uuid),
    GREATEST($1::uuid, $2::uuid),
    1, NOW(), NOW()
)
ON CONFLICT (user_a_id, user_b_id) DO UPDATE
SET raw_score = pair_intimacy.raw_score + 1,
    last_hug_at = NOW()
RETURNING user_a_id, user_b_id, raw_score, last_hug_at, last_decay_at
`

type UpsertPairIntimacyParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) UpsertPairIntimacy(ctx context.Context, arg UpsertPairIntimacyParams) (PairIntimacy, error) {
	row := q.db.QueryRow(ctx, upsertPairIntimacy, arg.UserA, arg.UserB)
	var i PairIntimacy
	err := row.Scan(
		&i.UserAID,
		&i.UserBID,
		&i.RawScore,
		&i.LastHugAt,
		&i.LastDecayAt,
	)
	return i, err
}
