// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: note.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserNote = `-- name: DeleteUserNote :exec
DELETE FROM user_notes
WHERE author_id = $1 AND target_id = $2
`

type DeleteUserNoteParams struct {
	AuthorID uuid.UUID
	TargetID uuid.UUID
}

func (q *Queries) DeleteUserNote(ctx context.Context, arg DeleteUserNoteParams) error {
	_, err := q.db.Exec(ctx, deleteUserNote, arg.AuthorID, arg.TargetID)
	return err
}

const getUserNote = `-- name: GetUserNote :one
SELECT author_id, target_id, content, updated_at
FROM user_notes
WHERE author_id = $1 AND target_id = $2
`

type GetUserNoteParams struct {
	AuthorID uuid.UUID
	TargetID uuid.UUID
}

func (q *Queries) GetUserNote(ctx context.Context, arg GetUserNoteParams) (UserNote, error) {
	row := q.db.QueryRow(ctx, getUserNote, arg.AuthorID, arg.TargetID)
	var i UserNote
	err := row.Scan(
		&i.AuthorID,
		&i.TargetID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserNotes = `-- name: ListUserNotes :many
SELECT n.author_id, n.target_id, n.content, n.updated_at,
       u.username AS target_username, u.display_name AS target_display_name
FROM user_notes n
JOIN users u ON u.id = n.target_id
WHERE n.author_id = $1
ORDER BY n.updated_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListUserNotesParams struct {
	AuthorID uuid.UUID
	Off      int32
	Lim      int32
}

type ListUserNotesRow struct {
	AuthorID          uuid.UUID
	TargetID          uuid.UUID
	Content           string
	UpdatedAt         pgtype.Timestamptz
	TargetUsername    string
	TargetDisplayName pgtype.Text
}

func (q *Queries) ListUserNotes(ctx context.Context, arg ListUserNotesParams) ([]ListUserNotesRow, error) {
	rows, err := q.db.Query(ctx, listUserNotes, arg.AuthorID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserNotesRow
	for rows.Next() {
		var i ListUserNotesRow
		if err := rows.Scan(
			&i.AuthorID,
			&i.TargetID,
			&i.Content,
			&i.UpdatedAt,
			&i.TargetUsername,
			&i.TargetDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserNote = `-- name: UpsertUserNote :one
INSERT INTO user_notes (author_id, target_id, content, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (author_id, target_id) DO UPDATE
    SET content = EXCLUDED.content,
        updated_at = NOW()
RETURNING author_id, target_id, content, updated_at
`

type UpsertUserNoteParams struct {
	AuthorID uuid.UUID
	TargetID uuid.UUID
	Content  string
}

func (q *Queries) UpsertUserNote(ctx context.Context, arg UpsertUserNoteParams) (UserNote, error) {
	row := q.db.QueryRow(ctx, upsertUserNote, arg.AuthorID, arg.TargetID, arg.Content)
	var i UserNote
	err := row.Scan(
		&i.AuthorID,
		&i.TargetID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}
