// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pair_streaks.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPairStreak = `-- name: GetPairStreak :one
SELECT user_a_id, user_b_id, current_streak, best_streak,
       last_streak_date, a_hugged_today, b_hugged_today, today_date
FROM pair_streaks
WHERE user_a_id = LEAST($1::uuid, $2::uuid)
  AND user_b_id = GREATEST($1::uuid, $2::uuid)
`

type GetPairStreakParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) GetPairStreak(ctx context.Context, arg GetPairStreakParams) (PairStreak, error) {
	row := q.db.QueryRow(ctx, getPairStreak, arg.UserA, arg.UserB)
	var i PairStreak
	err := row.Scan(
		&i.UserAID,
		&i.UserBID,
		&i.CurrentStreak,
		&i.BestStreak,
		&i.LastStreakDate,
		&i.AHuggedToday,
		&i.BHuggedToday,
		&i.TodayDate,
	)
	return i, err
}

const getPairStreakCalendar = `-- name: GetPairStreakCalendar :many
SELECT
    (COALESCE(h.accepted_at, h.created_at))::date AS hug_date,
    COUNT(*)::bigint AS hug_count,
    (COUNT(*) FILTER (WHERE h.giver_id = $1::uuid) > 0
     AND COUNT(*) FILTER (WHERE h.giver_id = $2::uuid) > 0)::bool AS completed
FROM hugs h
WHERE ((h.giver_id = $1::uuid AND h.receiver_id = $2::uuid)
   OR (h.giver_id = $2::uuid AND h.receiver_id = $1::uuid))
  AND h.status = 'completed'
  AND COALESCE(h.accepted_at, h.created_at) >= $3::timestamptz
GROUP BY hug_date
ORDER BY hug_date
`

type GetPairStreakCalendarParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
	Since pgtype.Timestamptz
}

type GetPairStreakCalendarRow struct {
	HugDate   pgtype.Date
	HugCount  int64
	Completed bool
}

func (q *Queries) GetPairStreakCalendar(ctx context.Context, arg GetPairStreakCalendarParams) ([]GetPairStreakCalendarRow, error) {
	rows, err := q.db.Query(ctx, getPairStreakCalendar, arg.UserA, arg.UserB, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPairStreakCalendarRow
	for rows.Next() {
		var i GetPairStreakCalendarRow
		if err := rows.Scan(&i.HugDate, &i.HugCount, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTopStreaks = `-- name: GetUserTopStreaks :many
SELECT
    ps.user_a_id,
    ps.user_b_id,
    ps.current_streak,
    ps.best_streak,
    ps.last_streak_date,
    ps.a_hugged_today,
    ps.b_hugged_today,
    ps.today_date,
    u.username AS other_username,
    u.display_name AS other_display_name,
    u.gender AS other_gender
FROM pair_streaks ps
JOIN users u ON u.id = CASE
    WHEN ps.user_a_id = $1::uuid THEN ps.user_b_id
    ELSE ps.user_a_id
END
WHERE (ps.user_a_id = $1::uuid OR ps.user_b_id = $1::uuid)
  AND ps.current_streak > 0
ORDER BY ps.current_streak DESC
LIMIT $2::int
`

type GetUserTopStreaksParams struct {
	UserID uuid.UUID
	Lim    int32
}

type GetUserTopStreaksRow struct {
	UserAID          uuid.UUID
	UserBID          uuid.UUID
	CurrentStreak    int32
	BestStreak       int32
	LastStreakDate   pgtype.Date
	AHuggedToday     bool
	BHuggedToday     bool
	TodayDate        pgtype.Date
	OtherUsername    string
	OtherDisplayName pgtype.Text
	OtherGender      pgtype.Text
}

func (q *Queries) GetUserTopStreaks(ctx context.Context, arg GetUserTopStreaksParams) ([]GetUserTopStreaksRow, error) {
	rows, err := q.db.Query(ctx, getUserTopStreaks, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTopStreaksRow
	for rows.Next() {
		var i GetUserTopStreaksRow
		if err := rows.Scan(
			&i.UserAID,
			&i.UserBID,
			&i.CurrentStreak,
			&i.BestStreak,
			&i.LastStreakDate,
			&i.AHuggedToday,
			&i.BHuggedToday,
			&i.TodayDate,
			&i.OtherUsername,
			&i.OtherDisplayName,
			&i.OtherGender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPairStreak = `-- name: UpsertPairStreak :one
INSERT INTO pair_streaks (user_a_id, user_b_id, current_streak, best_streak,
                          last_streak_date, a_hugged_today, b_hugged_today, today_date)
VALUES (
    LEAST($1::uuid, $2::uuid),
    GREATEST($1::uuid, $2::uuid),
    $3::int,
    $4::int,
    $5::date,
    $6::bool,
    $7::bool,
    $8::date
)
ON CONFLICT (user_a_id, user_b_id) DO UPDATE
SET current_streak = $3::int,
    best_streak = $4::int,
    last_streak_date = $5::date,
    a_hugged_today = $6::bool,
    b_hugged_today = $7::bool,
    today_date = $8::date
RETURNING user_a_id, user_b_id, current_streak, best_streak, last_streak_date, a_hugged_today, b_hugged_today, today_date
`

type UpsertPairStreakParams struct {
	UserA          uuid.UUID
	UserB          uuid.UUID
	CurrentStreak  int32
	BestStreak     int32
	LastStreakDate pgtype.Date
	AHuggedToday   bool
	BHuggedToday   bool
	TodayDate      pgtype.Date
}

func (q *Queries) UpsertPairStreak(ctx context.Context, arg UpsertPairStreakParams) (PairStreak, error) {
	row := q.db.QueryRow(ctx, upsertPairStreak,
		arg.UserA,
		arg.UserB,
		arg.CurrentStreak,
		arg.BestStreak,
		arg.LastStreakDate,
		arg.AHuggedToday,
		arg.BHuggedToday,
		arg.TodayDate,
	)
	var i PairStreak
	err := row.Scan(
		&i.UserAID,
		&i.UserBID,
		&i.CurrentStreak,
		&i.BestStreak,
		&i.LastStreakDate,
		&i.AHuggedToday,
		&i.BHuggedToday,
		&i.TodayDate,
	)
	return i, err
}
