// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sudoku.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSudokuCaptcha = `-- name: CreateSudokuCaptcha :one
INSERT INTO sudoku_captchas (user_id, puzzle, solution, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, puzzle, solution, errors, passed, expires_at, created_at
`

type CreateSudokuCaptchaParams struct {
	UserID    uuid.UUID
	Puzzle    []byte
	Solution  []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSudokuCaptcha(ctx context.Context, arg CreateSudokuCaptchaParams) (SudokuCaptcha, error) {
	row := q.db.QueryRow(ctx, createSudokuCaptcha,
		arg.UserID,
		arg.Puzzle,
		arg.Solution,
		arg.ExpiresAt,
	)
	var i SudokuCaptcha
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Puzzle,
		&i.Solution,
		&i.Errors,
		&i.Passed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSudokuCaptcha = `-- name: DeleteSudokuCaptcha :exec
DELETE FROM sudoku_captchas
WHERE id = $1
`

func (q *Queries) DeleteSudokuCaptcha(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSudokuCaptcha, id)
	return err
}

const getSudokuCaptcha = `-- name: GetSudokuCaptcha :one
SELECT id, user_id, puzzle, solution, errors, passed, expires_at, created_at
FROM sudoku_captchas
WHERE id = $1
`

func (q *Queries) GetSudokuCaptcha(ctx context.Context, id uuid.UUID) (SudokuCaptcha, error) {
	row := q.db.QueryRow(ctx, getSudokuCaptcha, id)
	var i SudokuCaptcha
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Puzzle,
		&i.Solution,
		&i.Errors,
		&i.Passed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementSudokuErrors = `-- name: IncrementSudokuErrors :one
UPDATE sudoku_captchas
SET errors = errors + 1
WHERE id = $1
RETURNING id, user_id, puzzle, solution, errors, passed, expires_at, created_at
`

func (q *Queries) IncrementSudokuErrors(ctx context.Context, id uuid.UUID) (SudokuCaptcha, error) {
	row := q.db.QueryRow(ctx, incrementSudokuErrors, id)
	var i SudokuCaptcha
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Puzzle,
		&i.Solution,
		&i.Errors,
		&i.Passed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markSudokuPassed = `-- name: MarkSudokuPassed :one
UPDATE sudoku_captchas
SET passed = TRUE
WHERE id = $1
RETURNING id, user_id, puzzle, solution, errors, passed, expires_at, created_at
`

func (q *Queries) MarkSudokuPassed(ctx context.Context, id uuid.UUID) (SudokuCaptcha, error) {
	row := q.db.QueryRow(ctx, markSudokuPassed, id)
	var i SudokuCaptcha
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Puzzle,
		&i.Solution,
		&i.Errors,
		&i.Passed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
