// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminClearPromotion = `-- name: AdminClearPromotion :one
UPDATE users
SET promoted_until = NULL, promotion_message = NULL, promotion_bid = 0
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

func (q *Queries) AdminClearPromotion(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, adminClearPromotion, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const adminDeleteUser = `-- name: AdminDeleteUser :execrows
DELETE FROM users
WHERE id = $1 AND role != 'admin'
`

func (q *Queries) AdminDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateCaptchaType = `-- name: AdminUpdateCaptchaType :one
UPDATE users
SET captcha_type = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type AdminUpdateCaptchaTypeParams struct {
	ID          uuid.UUID
	CaptchaType string
}

func (q *Queries) AdminUpdateCaptchaType(ctx context.Context, arg AdminUpdateCaptchaTypeParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateCaptchaType, arg.ID, arg.CaptchaType)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const adminUpdateDisplayName = `-- name: AdminUpdateDisplayName :one
UPDATE users
SET display_name = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type AdminUpdateDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName pgtype.Text
}

func (q *Queries) AdminUpdateDisplayName(ctx context.Context, arg AdminUpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const adminUpdateGender = `-- name: AdminUpdateGender :one
UPDATE users
SET gender = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type AdminUpdateGenderParams struct {
	ID     uuid.UUID
	Gender pgtype.Text
}

func (q *Queries) AdminUpdateGender(ctx context.Context, arg AdminUpdateGenderParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateGender, arg.ID, arg.Gender)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const adminUpdatePassword = `-- name: AdminUpdatePassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type AdminUpdatePasswordParams struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) AdminUpdatePassword(ctx context.Context, arg AdminUpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, adminUpdatePassword, arg.ID, arg.Password)
	return err
}

const adminUpdateSpecialTag = `-- name: AdminUpdateSpecialTag :one
UPDATE users
SET special_tag = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type AdminUpdateSpecialTagParams struct {
	ID         uuid.UUID
	SpecialTag pgtype.Text
}

func (q *Queries) AdminUpdateSpecialTag(ctx context.Context, arg AdminUpdateSpecialTagParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateSpecialTag, arg.ID, arg.SpecialTag)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const adminUpdateTag = `-- name: AdminUpdateTag :one
UPDATE users
SET tag = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type AdminUpdateTagParams struct {
	ID  uuid.UUID
	Tag pgtype.Text
}

func (q *Queries) AdminUpdateTag(ctx context.Context, arg AdminUpdateTagParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateTag, arg.ID, arg.Tag)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const adminUpdateUsername = `-- name: AdminUpdateUsername :one
UPDATE users
SET username = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type AdminUpdateUsernameParams struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) AdminUpdateUsername(ctx context.Context, arg AdminUpdateUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const banUser = `-- name: BanUser :one
UPDATE users
SET banned_at = NOW()
WHERE id = $1 AND role != 'admin'
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

func (q *Queries) BanUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, banUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const clearExpiredPromotions = `-- name: ClearExpiredPromotions :execrows
UPDATE users
SET promoted_until = NULL, promotion_message = NULL, promotion_bid = 0
WHERE promoted_until < NOW()
`

func (q *Queries) ClearExpiredPromotions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, clearExpiredPromotions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearUserTelegramID = `-- name: ClearUserTelegramID :one
UPDATE users
SET telegram_id = NULL
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

func (q *Queries) ClearUserTelegramID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, clearUserTelegramID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const countBannedUsers = `-- name: CountBannedUsers :one
SELECT COUNT(*) FROM users WHERE banned_at IS NOT NULL
`

func (q *Queries) CountBannedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBannedUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, role, gender, created_at)
VALUES (
    $1, $2, $3, $4, NOW()
)
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type CreateUserParams struct {
	Username string
	Password string
	Role     string
	Gender   pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT
    u.id,
    u.username,
    u.role,
    u.gender,
    u.display_name,
    u.tag,
    u.special_tag,
    COALESCE(given.cnt, 0) + COALESCE(received.cnt, 0) AS total_hugs,
    COALESCE(given.cnt, 0) AS hugs_given,
    COALESCE(received.cnt, 0) AS hugs_received
FROM users u
LEFT JOIN (
    SELECT giver_id, COUNT(*) AS cnt FROM hugs WHERE status = 'completed' GROUP BY giver_id
) given ON given.giver_id = u.id
LEFT JOIN (
    SELECT receiver_id, COUNT(*) AS cnt FROM hugs WHERE status = 'completed' GROUP BY receiver_id
) received ON received.receiver_id = u.id
WHERE u.banned_at IS NULL
ORDER BY total_hugs DESC
LIMIT $2::int OFFSET $1::int
`

type GetLeaderboardParams struct {
	Off int32
	Lim int32
}

type GetLeaderboardRow struct {
	ID           uuid.UUID
	Username     string
	Role         string
	Gender       pgtype.Text
	DisplayName  pgtype.Text
	Tag          pgtype.Text
	SpecialTag   pgtype.Text
	TotalHugs    int32
	HugsGiven    int64
	HugsReceived int64
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.DisplayName,
			&i.Tag,
			&i.SpecialTag,
			&i.TotalHugs,
			&i.HugsGiven,
			&i.HugsReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentHugsFeed = `-- name: GetRecentHugsFeed :many
SELECT
    h.id,
    h.giver_id,
    h.receiver_id,
    COALESCE(h.accepted_at, h.created_at) AS created_at,
    h.hug_type,
    (h.comment IS NOT NULL)::bool AS has_comment,
    h.streak_tier,
    g.username AS giver_username,
    r.username AS receiver_username,
    g.gender AS giver_gender,
    g.display_name AS giver_display_name,
    r.display_name AS receiver_display_name
FROM hugs h
JOIN users g ON g.id = h.giver_id
JOIN users r ON r.id = h.receiver_id
WHERE h.status = 'completed'
ORDER BY COALESCE(h.accepted_at, h.created_at) DESC
LIMIT $2::int OFFSET $1::int
`

type GetRecentHugsFeedParams struct {
	Off int32
	Lim int32
}

type GetRecentHugsFeedRow struct {
	ID                  uuid.UUID
	GiverID             uuid.UUID
	ReceiverID          uuid.UUID
	CreatedAt           pgtype.Timestamptz
	HugType             string
	HasComment          bool
	StreakTier          string
	GiverUsername       string
	ReceiverUsername    string
	GiverGender         pgtype.Text
	GiverDisplayName    pgtype.Text
	ReceiverDisplayName pgtype.Text
}

func (q *Queries) GetRecentHugsFeed(ctx context.Context, arg GetRecentHugsFeedParams) ([]GetRecentHugsFeedRow, error) {
	rows, err := q.db.Query(ctx, getRecentHugsFeed, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentHugsFeedRow
	for rows.Next() {
		var i GetRecentHugsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.GiverID,
			&i.ReceiverID,
			&i.CreatedAt,
			&i.HugType,
			&i.HasComment,
			&i.StreakTier,
			&i.GiverUsername,
			&i.ReceiverUsername,
			&i.GiverGender,
			&i.GiverDisplayName,
			&i.ReceiverDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    u.id, u.username, u.password, u.role, u.gender, u.banned_at, u.hug_slots, u.created_at, u.display_name, u.telegram_id, u.tag, u.special_tag, u.captcha_cooldown_until, u.captcha_type, u.promoted_until, u.promotion_message, u.promotion_bid, u.vip_remaining_seconds, u.vip_cooldown_until, 
    COALESCE(b.amount, 0)::int AS balance,
    COALESCE((
        SELECT AVG(EXTRACT(EPOCH FROM (h.accepted_at - h.created_at)))
        FROM (
            SELECT accepted_at, created_at
            FROM hugs
            WHERE receiver_id = u.id AND status = 'completed'
            ORDER BY created_at DESC
            LIMIT 30
        ) h
    ), -1)::float AS avg_response_time
FROM users u
LEFT JOIN balances b ON b.user_id = u.id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID                   uuid.UUID
	Username             string
	Password             string
	Role                 string
	Gender               pgtype.Text
	BannedAt             pgtype.Timestamptz
	HugSlots             int32
	CreatedAt            pgtype.Timestamptz
	DisplayName          pgtype.Text
	TelegramID           pgtype.Int8
	Tag                  pgtype.Text
	SpecialTag           pgtype.Text
	CaptchaCooldownUntil pgtype.Timestamptz
	CaptchaType          string
	PromotedUntil        pgtype.Timestamptz
	PromotionMessage     pgtype.Text
	PromotionBid         int32
	VipRemainingSeconds  int32
	VipCooldownUntil     pgtype.Timestamptz
	Balance              int32
	AvgResponseTime      float64
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
		&i.Balance,
		&i.AvgResponseTime,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT 
    u.id, u.username, u.password, u.role, u.gender, u.banned_at, u.hug_slots, u.created_at, u.display_name, u.telegram_id, u.tag, u.special_tag, u.captcha_cooldown_until, u.captcha_type, u.promoted_until, u.promotion_message, u.promotion_bid, u.vip_remaining_seconds, u.vip_cooldown_until, 
    COALESCE(b.amount, 0)::int AS balance,
    COALESCE((
        SELECT AVG(EXTRACT(EPOCH FROM (h.accepted_at - h.created_at)))
        FROM (
            SELECT accepted_at, created_at
            FROM hugs
            WHERE receiver_id = u.id AND status = 'completed'
            ORDER BY created_at DESC
            LIMIT 30
        ) h
    ), -1)::float AS avg_response_time
FROM users u
LEFT JOIN balances b ON b.user_id = u.id
WHERE u.telegram_id = $1
`

type GetUserByTelegramIDRow struct {
	ID                   uuid.UUID
	Username             string
	Password             string
	Role                 string
	Gender               pgtype.Text
	BannedAt             pgtype.Timestamptz
	HugSlots             int32
	CreatedAt            pgtype.Timestamptz
	DisplayName          pgtype.Text
	TelegramID           pgtype.Int8
	Tag                  pgtype.Text
	SpecialTag           pgtype.Text
	CaptchaCooldownUntil pgtype.Timestamptz
	CaptchaType          string
	PromotedUntil        pgtype.Timestamptz
	PromotionMessage     pgtype.Text
	PromotionBid         int32
	VipRemainingSeconds  int32
	VipCooldownUntil     pgtype.Timestamptz
	Balance              int32
	AvgResponseTime      float64
}

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID pgtype.Int8) (GetUserByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i GetUserByTelegramIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
		&i.Balance,
		&i.AvgResponseTime,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    u.id, u.username, u.password, u.role, u.gender, u.banned_at, u.hug_slots, u.created_at, u.display_name, u.telegram_id, u.tag, u.special_tag, u.captcha_cooldown_until, u.captcha_type, u.promoted_until, u.promotion_message, u.promotion_bid, u.vip_remaining_seconds, u.vip_cooldown_until, 
    COALESCE(b.amount, 0)::int AS balance,
    COALESCE((
        SELECT AVG(EXTRACT(EPOCH FROM (h.accepted_at - h.created_at)))
        FROM (
            SELECT accepted_at, created_at
            FROM hugs
            WHERE receiver_id = u.id AND status = 'completed'
            ORDER BY created_at DESC
            LIMIT 30
        ) h
    ), -1)::float AS avg_response_time
FROM users u
LEFT JOIN balances b ON b.user_id = u.id
WHERE u.username = $1
`

type GetUserByUsernameRow struct {
	ID                   uuid.UUID
	Username             string
	Password             string
	Role                 string
	Gender               pgtype.Text
	BannedAt             pgtype.Timestamptz
	HugSlots             int32
	CreatedAt            pgtype.Timestamptz
	DisplayName          pgtype.Text
	TelegramID           pgtype.Int8
	Tag                  pgtype.Text
	SpecialTag           pgtype.Text
	CaptchaCooldownUntil pgtype.Timestamptz
	CaptchaType          string
	PromotedUntil        pgtype.Timestamptz
	PromotionMessage     pgtype.Text
	PromotionBid         int32
	VipRemainingSeconds  int32
	VipCooldownUntil     pgtype.Timestamptz
	Balance              int32
	AvgResponseTime      float64
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
		&i.Balance,
		&i.AvgResponseTime,
	)
	return i, err
}

const getUserSlots = `-- name: GetUserSlots :one
SELECT hug_slots FROM users WHERE id = $1
`

func (q *Queries) GetUserSlots(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUserSlots, id)
	var hug_slots int32
	err := row.Scan(&hug_slots)
	return hug_slots, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COUNT(*) FILTER (WHERE giver_id = $1::uuid)::bigint AS hugs_given,
    COUNT(*) FILTER (WHERE receiver_id = $1::uuid)::bigint AS hugs_received,
    COUNT(*)::bigint AS total_hugs
FROM hugs
WHERE (giver_id = $1::uuid OR receiver_id = $1::uuid)
  AND status = 'completed'
`

type GetUserStatsRow struct {
	HugsGiven    int64
	HugsReceived int64
	TotalHugs    int64
}

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.HugsGiven, &i.HugsReceived, &i.TotalHugs)
	return i, err
}

const getUserTelegramID = `-- name: GetUserTelegramID :one
SELECT telegram_id FROM users WHERE id = $1
`

func (q *Queries) GetUserTelegramID(ctx context.Context, id uuid.UUID) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getUserTelegramID, id)
	var telegram_id pgtype.Int8
	err := row.Scan(&telegram_id)
	return telegram_id, err
}

const incrementUserSlots = `-- name: IncrementUserSlots :one
UPDATE users
SET hug_slots = hug_slots + 1
WHERE id = $1 AND hug_slots < 5
RETURNING hug_slots
`

func (q *Queries) IncrementUserSlots(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementUserSlots, id)
	var hug_slots int32
	err := row.Scan(&hug_slots)
	return hug_slots, err
}

const isTelegramIDTaken = `-- name: IsTelegramIDTaken :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE telegram_id = $1 AND id != $2
) AS taken
`

type IsTelegramIDTakenParams struct {
	TelegramID pgtype.Int8
	ID         uuid.UUID
}

func (q *Queries) IsTelegramIDTaken(ctx context.Context, arg IsTelegramIDTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTelegramIDTaken, arg.TelegramID, arg.ID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT 
    u.id, u.username, u.role, u.gender, u.display_name, u.tag, u.special_tag,
    (u.telegram_id IS NOT NULL)::bool AS is_telegram_linked,
    u.promoted_until, u.promotion_message, u.promotion_bid,
    u.vip_remaining_seconds, u.vip_cooldown_until,
    (EXISTS (
        SELECT 1 FROM hugs 
        WHERE receiver_id = u.id AND status = 'completed' AND accepted_at > NOW() - interval '3 days'
    ))::bool AS is_recently_active,
    COALESCE((
        SELECT AVG(EXTRACT(EPOCH FROM (h.accepted_at - h.created_at)))
        FROM (
            SELECT accepted_at, created_at
            FROM hugs
            WHERE receiver_id = u.id AND status = 'completed'
            ORDER BY created_at DESC
            LIMIT 30
        ) h
    ), -1)::float AS avg_response_time
FROM users u
LEFT JOIN LATERAL (
    SELECT MAX(created_at) AS last_visit
    FROM refresh_tokens
    WHERE user_id = u.id
) rt ON true
WHERE u.banned_at IS NULL
  AND u.id NOT IN (
    SELECT blocked_id FROM user_blocks WHERE blocker_id = $1::uuid
    UNION
    SELECT blocker_id FROM user_blocks WHERE blocked_id = $1::uuid
  )
ORDER BY 
    (u.promoted_until > NOW()) DESC,
    u.promotion_bid DESC,
    (EXISTS (
        SELECT 1 FROM hugs 
        WHERE receiver_id = u.id AND status = 'completed' AND accepted_at > NOW() - interval '3 days'
    )) DESC,
    (
        SELECT AVG(EXTRACT(EPOCH FROM (h.accepted_at - h.created_at)))
        FROM (
            SELECT accepted_at, created_at
            FROM hugs
            WHERE receiver_id = u.id AND status = 'completed'
            ORDER BY created_at DESC
            LIMIT 30
        ) h
    ) ASC NULLS LAST,
    COALESCE(rt.last_visit, u.created_at) DESC NULLS LAST
LIMIT $3::int OFFSET $2::int
`

type ListAllUsersParams struct {
	ViewerID uuid.UUID
	Off      int32
	Lim      int32
}

type ListAllUsersRow struct {
	ID                  uuid.UUID
	Username            string
	Role                string
	Gender              pgtype.Text
	DisplayName         pgtype.Text
	Tag                 pgtype.Text
	SpecialTag          pgtype.Text
	IsTelegramLinked    bool
	PromotedUntil       pgtype.Timestamptz
	PromotionMessage    pgtype.Text
	PromotionBid        int32
	VipRemainingSeconds int32
	VipCooldownUntil    pgtype.Timestamptz
	IsRecentlyActive    bool
	AvgResponseTime     float64
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.ViewerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.DisplayName,
			&i.Tag,
			&i.SpecialTag,
			&i.IsTelegramLinked,
			&i.PromotedUntil,
			&i.PromotionMessage,
			&i.PromotionBid,
			&i.VipRemainingSeconds,
			&i.VipCooldownUntil,
			&i.IsRecentlyActive,
			&i.AvgResponseTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT u.id, u.username, u.role, u.gender, u.display_name, u.tag, u.special_tag, u.banned_at, u.created_at, u.captcha_type, u.captcha_cooldown_until,
       u.promoted_until, u.promotion_message, u.promotion_bid,
    u.vip_remaining_seconds, u.vip_cooldown_until,
       COALESCE(b.amount, 0)::int AS balance,
       COALESCE(rt.last_visit, u.created_at)::timestamptz AS last_visit_at
FROM users u
LEFT JOIN balances b ON b.user_id = u.id
LEFT JOIN LATERAL (
    SELECT MAX(created_at) AS last_visit
    FROM refresh_tokens
    WHERE user_id = u.id
) rt ON true
ORDER BY last_visit_at DESC NULLS LAST
LIMIT $2::int OFFSET $1::int
`

type ListUsersAdminParams struct {
	Off int32
	Lim int32
}

type ListUsersAdminRow struct {
	ID                   uuid.UUID
	Username             string
	Role                 string
	Gender               pgtype.Text
	DisplayName          pgtype.Text
	Tag                  pgtype.Text
	SpecialTag           pgtype.Text
	BannedAt             pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	CaptchaType          string
	CaptchaCooldownUntil pgtype.Timestamptz
	PromotedUntil        pgtype.Timestamptz
	PromotionMessage     pgtype.Text
	PromotionBid         int32
	VipRemainingSeconds  int32
	VipCooldownUntil     pgtype.Timestamptz
	Balance              int32
	LastVisitAt          pgtype.Timestamptz
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminRow
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.DisplayName,
			&i.Tag,
			&i.SpecialTag,
			&i.BannedAt,
			&i.CreatedAt,
			&i.CaptchaType,
			&i.CaptchaCooldownUntil,
			&i.PromotedUntil,
			&i.PromotionMessage,
			&i.PromotionBid,
			&i.VipRemainingSeconds,
			&i.VipCooldownUntil,
			&i.Balance,
			&i.LastVisitAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVIPUsers = `-- name: ListVIPUsers :many
SELECT 
    u.id, u.username, u.role, u.gender, u.display_name, u.tag, u.special_tag,
    (u.telegram_id IS NOT NULL)::bool AS is_telegram_linked,
    u.promoted_until, u.promotion_message, u.promotion_bid,
    u.vip_remaining_seconds, u.vip_cooldown_until,
    (EXISTS (
        SELECT 1 FROM hugs 
        WHERE receiver_id = u.id AND status = 'completed' AND accepted_at > NOW() - interval '3 days'
    ))::bool AS is_recently_active,
    COALESCE((
        SELECT AVG(EXTRACT(EPOCH FROM (h.accepted_at - h.created_at)))
        FROM (
            SELECT accepted_at, created_at
            FROM hugs
            WHERE receiver_id = u.id AND status = 'completed'
            ORDER BY created_at DESC
            LIMIT 30
        ) h
    ), -1)::float AS avg_response_time
FROM users u
WHERE u.promoted_until > NOW() AND u.banned_at IS NULL
ORDER BY u.promotion_bid DESC
`

type ListVIPUsersRow struct {
	ID                  uuid.UUID
	Username            string
	Role                string
	Gender              pgtype.Text
	DisplayName         pgtype.Text
	Tag                 pgtype.Text
	SpecialTag          pgtype.Text
	IsTelegramLinked    bool
	PromotedUntil       pgtype.Timestamptz
	PromotionMessage    pgtype.Text
	PromotionBid        int32
	VipRemainingSeconds int32
	VipCooldownUntil    pgtype.Timestamptz
	IsRecentlyActive    bool
	AvgResponseTime     float64
}

func (q *Queries) ListVIPUsers(ctx context.Context) ([]ListVIPUsersRow, error) {
	rows, err := q.db.Query(ctx, listVIPUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVIPUsersRow
	for rows.Next() {
		var i ListVIPUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.DisplayName,
			&i.Tag,
			&i.SpecialTag,
			&i.IsTelegramLinked,
			&i.PromotedUntil,
			&i.PromotionMessage,
			&i.PromotionBid,
			&i.VipRemainingSeconds,
			&i.VipCooldownUntil,
			&i.IsRecentlyActive,
			&i.AvgResponseTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteUser = `-- name: PromoteUser :one
UPDATE users
SET promoted_until = $2, promotion_message = $3, promotion_bid = $4
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type PromoteUserParams struct {
	ID               uuid.UUID
	PromotedUntil    pgtype.Timestamptz
	PromotionMessage pgtype.Text
	PromotionBid     int32
}

func (q *Queries) PromoteUser(ctx context.Context, arg PromoteUserParams) (User, error) {
	row := q.db.QueryRow(ctx, promoteUser,
		arg.ID,
		arg.PromotedUntil,
		arg.PromotionMessage,
		arg.PromotionBid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT 
    u.id, u.username, u.role, u.gender, u.display_name, u.tag, u.special_tag,
    (u.telegram_id IS NOT NULL)::bool AS is_telegram_linked,
    u.promoted_until, u.promotion_message, u.promotion_bid,
    u.vip_remaining_seconds, u.vip_cooldown_until,
    (EXISTS (
        SELECT 1 FROM hugs 
        WHERE receiver_id = u.id AND status = 'completed' AND accepted_at > NOW() - interval '3 days'
    ))::bool AS is_recently_active,
    COALESCE((
        SELECT AVG(EXTRACT(EPOCH FROM (h.accepted_at - h.created_at)))
        FROM (
            SELECT accepted_at, created_at
            FROM hugs
            WHERE receiver_id = u.id AND status = 'completed'
            ORDER BY created_at DESC
            LIMIT 30
        ) h
    ), -1)::float AS avg_response_time
FROM users u
LEFT JOIN LATERAL (
    SELECT MAX(created_at) AS last_visit
    FROM refresh_tokens
    WHERE user_id = u.id
) rt ON true
WHERE (u.username ILIKE '%' || $1::text || '%' OR u.display_name ILIKE '%' || $1::text || '%')
  AND u.banned_at IS NULL
  AND u.id NOT IN (
    SELECT blocked_id FROM user_blocks WHERE blocker_id = $2::uuid
    UNION
    SELECT blocker_id FROM user_blocks WHERE blocked_id = $2::uuid
  )
ORDER BY 
    (u.promoted_until > NOW()) DESC,
    u.promotion_bid DESC,
    (EXISTS (
        SELECT 1 FROM hugs 
        WHERE receiver_id = u.id AND status = 'completed' AND accepted_at > NOW() - interval '3 days'
    )) DESC,
    (
        SELECT AVG(EXTRACT(EPOCH FROM (h.accepted_at - h.created_at)))
        FROM (
            SELECT accepted_at, created_at
            FROM hugs
            WHERE receiver_id = u.id AND status = 'completed'
            ORDER BY created_at DESC
            LIMIT 30
        ) h
    ) ASC NULLS LAST,
    COALESCE(rt.last_visit, u.created_at) DESC NULLS LAST
LIMIT $4::int OFFSET $3::int
`

type SearchUsersParams struct {
	Query    string
	ViewerID uuid.UUID
	Off      int32
	Lim      int32
}

type SearchUsersRow struct {
	ID                  uuid.UUID
	Username            string
	Role                string
	Gender              pgtype.Text
	DisplayName         pgtype.Text
	Tag                 pgtype.Text
	SpecialTag          pgtype.Text
	IsTelegramLinked    bool
	PromotedUntil       pgtype.Timestamptz
	PromotionMessage    pgtype.Text
	PromotionBid        int32
	VipRemainingSeconds int32
	VipCooldownUntil    pgtype.Timestamptz
	IsRecentlyActive    bool
	AvgResponseTime     float64
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Query,
		arg.ViewerID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.DisplayName,
			&i.Tag,
			&i.SpecialTag,
			&i.IsTelegramLinked,
			&i.PromotedUntil,
			&i.PromotionMessage,
			&i.PromotionBid,
			&i.VipRemainingSeconds,
			&i.VipCooldownUntil,
			&i.IsRecentlyActive,
			&i.AvgResponseTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersAdmin = `-- name: SearchUsersAdmin :many
SELECT u.id, u.username, u.role, u.gender, u.display_name, u.tag, u.special_tag, u.banned_at, u.created_at, u.captcha_type, u.captcha_cooldown_until,
       u.promoted_until, u.promotion_message, u.promotion_bid,
    u.vip_remaining_seconds, u.vip_cooldown_until,
       COALESCE(b.amount, 0)::int AS balance,
       COALESCE(rt.last_visit, u.created_at)::timestamptz AS last_visit_at
FROM users u
LEFT JOIN balances b ON b.user_id = u.id
LEFT JOIN LATERAL (
    SELECT MAX(created_at) AS last_visit
    FROM refresh_tokens
    WHERE user_id = u.id
) rt ON true
WHERE (u.username ILIKE '%' || $1::text || '%' OR u.display_name ILIKE '%' || $1::text || '%')
ORDER BY last_visit_at DESC NULLS LAST
LIMIT $3::int OFFSET $2::int
`

type SearchUsersAdminParams struct {
	Query string
	Off   int32
	Lim   int32
}

type SearchUsersAdminRow struct {
	ID                   uuid.UUID
	Username             string
	Role                 string
	Gender               pgtype.Text
	DisplayName          pgtype.Text
	Tag                  pgtype.Text
	SpecialTag           pgtype.Text
	BannedAt             pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	CaptchaType          string
	CaptchaCooldownUntil pgtype.Timestamptz
	PromotedUntil        pgtype.Timestamptz
	PromotionMessage     pgtype.Text
	PromotionBid         int32
	VipRemainingSeconds  int32
	VipCooldownUntil     pgtype.Timestamptz
	Balance              int32
	LastVisitAt          pgtype.Timestamptz
}

func (q *Queries) SearchUsersAdmin(ctx context.Context, arg SearchUsersAdminParams) ([]SearchUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdmin, arg.Query, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersAdminRow
	for rows.Next() {
		var i SearchUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.DisplayName,
			&i.Tag,
			&i.SpecialTag,
			&i.BannedAt,
			&i.CreatedAt,
			&i.CaptchaType,
			&i.CaptchaCooldownUntil,
			&i.PromotedUntil,
			&i.PromotionMessage,
			&i.PromotionBid,
			&i.VipRemainingSeconds,
			&i.VipCooldownUntil,
			&i.Balance,
			&i.LastVisitAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCaptchaCooldown = `-- name: SetCaptchaCooldown :exec
UPDATE users
SET captcha_cooldown_until = $2
WHERE id = $1
`

type SetCaptchaCooldownParams struct {
	ID                   uuid.UUID
	CaptchaCooldownUntil pgtype.Timestamptz
}

func (q *Queries) SetCaptchaCooldown(ctx context.Context, arg SetCaptchaCooldownParams) error {
	_, err := q.db.Exec(ctx, setCaptchaCooldown, arg.ID, arg.CaptchaCooldownUntil)
	return err
}

const setUserTelegramID = `-- name: SetUserTelegramID :one
UPDATE users
SET telegram_id = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type SetUserTelegramIDParams struct {
	ID         uuid.UUID
	TelegramID pgtype.Int8
}

func (q *Queries) SetUserTelegramID(ctx context.Context, arg SetUserTelegramIDParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserTelegramID, arg.ID, arg.TelegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const setVipCooldown = `-- name: SetVipCooldown :one
UPDATE users
SET vip_cooldown_until = $2, vip_remaining_seconds = $3
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type SetVipCooldownParams struct {
	ID                  uuid.UUID
	VipCooldownUntil    pgtype.Timestamptz
	VipRemainingSeconds int32
}

func (q *Queries) SetVipCooldown(ctx context.Context, arg SetVipCooldownParams) (User, error) {
	row := q.db.QueryRow(ctx, setVipCooldown, arg.ID, arg.VipCooldownUntil, arg.VipRemainingSeconds)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const unbanUser = `-- name: UnbanUser :one
UPDATE users
SET banned_at = NULL
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

func (q *Queries) UnbanUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, unbanUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET gender = $2, display_name = $3, tag = $4
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type UpdateUserSettingsParams struct {
	ID          uuid.UUID
	Gender      pgtype.Text
	DisplayName pgtype.Text
	Tag         pgtype.Text
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.ID,
		arg.Gender,
		arg.DisplayName,
		arg.Tag,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}

const updateVipBudget = `-- name: UpdateVipBudget :one
UPDATE users
SET vip_remaining_seconds = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots, created_at, display_name, telegram_id, tag, special_tag, captcha_cooldown_until, captcha_type, promoted_until, promotion_message, promotion_bid, vip_remaining_seconds, vip_cooldown_until
`

type UpdateVipBudgetParams struct {
	ID                  uuid.UUID
	VipRemainingSeconds int32
}

func (q *Queries) UpdateVipBudget(ctx context.Context, arg UpdateVipBudgetParams) (User, error) {
	row := q.db.QueryRow(ctx, updateVipBudget, arg.ID, arg.VipRemainingSeconds)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
		&i.CreatedAt,
		&i.DisplayName,
		&i.TelegramID,
		&i.Tag,
		&i.SpecialTag,
		&i.CaptchaCooldownUntil,
		&i.CaptchaType,
		&i.PromotedUntil,
		&i.PromotionMessage,
		&i.PromotionBid,
		&i.VipRemainingSeconds,
		&i.VipCooldownUntil,
	)
	return i, err
}
